### ISSUE TITLE
Analogwrite not working on MSP432 on P6.5 and P6.4

### ISSUE THREAD

**Issue by fcooper** [energia/Energia#1011]
* LaunchPad board name and version: MSP432 Red v2.1
* Energia IDE version (found in Energia > About Energia menu): 1.6.10E18
* Board package version (found in Tools > Boards > Boards Manager menu): 5.6.1
* OS name and version: Windows 10 64bit

### Describe the expected results.

PWM output on P6.4 and P6.5 when using analogWrite, The MSP432 pinmap indicates that those pins are valid for analogwrite.

### Describe the actual results.

No PWM output on pins P6.4 and P6.5. Verified by connecting logic analyzer to pins. When connected to those pins I see no output. When changing to other pins capable of analogwrite I see a square wave. Confirmed that the pins do work but toggling them using digitalWrites. 

### List the steps to reproduce the problem.

```
#define LED RED_LED
int left_pwm_pin = 10;  // P6.5

void setup() {                

pinMode(LED, OUTPUT);   
pinMode(left_pwm_pin, OUTPUT);      // sets the digital pin as output
analogWrite(left_pwm_pin, 125);
}

void loop() {
  digitalWrite(LED, HIGH);   // turn the LED on (HIGH is the voltage level)
  delay(1000);               // wait for a second
  digitalWrite(LED, LOW);    // turn the LED off by making the voltage LOW
  delay(1000);               // wait for a second
}
```

**Comment by robertinant** [comment]
The pinmap is incorrect. P6.4/P6.5 are not PWM capable. Fixed with https://github.com/energia/energia.nu/commit/2b461aa5a99a750f8d3b102adbf2551ee2dd02f5

**Comment by rei-vilo** [comment]
Updated pins map

<img width="1094" alt="msp432p401r" src="https://user-images.githubusercontent.com/951776/48512791-9dfb6880-e85a-11e8-9c12-cf382b88b76d.png">
