### ISSUE TITLE
Issue Building Energia on MacOSX V10.13.14

### ISSUE THREAD

**Issue by jseals** [energia/Energia#1012]
A similar issue was reported for the High Sierra Beta as I see in this forum, but in the actual release there is still an issue.

### Please provide the following information.

* LaunchPad board name and version: MSP432P401R
* Energia IDE version (found in Energia > About Energia menu): 1.6.10E18
* Board package version (found in Tools > Boards > Boards Manager menu): LaunchPad w/MSP432 EMT (48MHz)
* OS name and version: MacOSX V10.13.14 High Sierra

### Describe the expected results.

I expected to be able to build the basic Blink project.

### Describe the actual results.

I get an error code, shown at the bottom

MacOSX V

### List the steps to reproduce the problem.

I press Verify.

Energia: 1.6.10E18 (Mac OS X), Board: "LaunchPad w/ msp432 EMT (48MHz)"

failed MSpanList_Insert 0x30d000 0x1891650d3c09 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x2ad50b)
	/usr/local/go/src/runtime/panic.go:491 +0xad fp=0x7ffeefbff440 sp=0x7ffeefbff410
runtime.MSpanList_Insert(0x2cb168, 0x30d000)
	/usr/local/go/src/runtime/mheap.c:692 +0x8f fp=0x7ffeefbff468 sp=0x7ffeefbff440
MHeap_FreeSpanLocked(0x2c7d60, 0x30d000, 0x100)
	/usr/local/go/src/runtime/mheap.c:583 +0x163 fp=0x7ffeefbff4a8 sp=0x7ffeefbff468
MHeap_Grow(0x2c7d60, 0x8, 0x0)
	/usr/local/go/src/runtime/mheap.c:420 +0x1a8 fp=0x7ffeefbff4e8 sp=0x7ffeefbff4a8
MHeap_AllocSpanLocked(0x2c7d60, 0x1, 0x0)
	/usr/local/go/src/runtime/mheap.c:298 +0x365 fp=0x7ffeefbff528 sp=0x7ffeefbff4e8
mheap_alloc(0x2c7d60, 0x1, 0x12, 0x0)
	/usr/local/go/src/runtime/mheap.c:190 +0x121 fp=0x7ffeefbff550 sp=0x7ffeefbff528
runtime.MHeap_Alloc(0x2c7d60, 0x1, 0x10000000012, 0xf989)
	/usr/local/go/src/runtime/mheap.c:240 +0x66 fp=0x7ffeefbff588 sp=0x7ffeefbff550
MCentral_Grow(0x2cfad8, 0x0)
	/usr/local/go/src/runtime/mcentral.c:197 +0x8b fp=0x7ffeefbff5f0 sp=0x7ffeefbff588
runtime.MCentral_CacheSpan(0x2cfad8, 0x0)
	/usr/local/go/src/runtime/mcentral.c:85 +0x167 fp=0x7ffeefbff628 sp=0x7ffeefbff5f0
runtime.MCache_Refill(0x309000, 0x12, 0x0)
	/usr/local/go/src/runtime/mcache.c:90 +0xa0 fp=0x7ffeefbff650 sp=0x7ffeefbff628
runtime.mcacheRefill_m()
	/usr/local/go/src/runtime/malloc.c:368 +0x57 fp=0x7ffeefbff670 sp=0x7ffeefbff650
runtime.onM(0x224f58)
	/usr/local/go/src/runtime/asm_amd64.s:273 +0x9a fp=0x7ffeefbff678 sp=0x7ffeefbff670
runtime.mallocgc(0x120, 0x1beba0, 0x0, 0x0)
	/usr/local/go/src/runtime/malloc.go:178 +0x849 fp=0x7ffeefbff728 sp=0x7ffeefbff678
runtime.newobject(0x1beba0, 0x309000)
	/usr/local/go/src/runtime/malloc.go:353 +0x49 fp=0x7ffeefbff750 sp=0x7ffeefbff728
runtime.newG(0x276ba)
	/usr/local/go/src/runtime/proc.go:233 +0x2a fp=0x7ffeefbff768 sp=0x7ffeefbff750
allocg(0x2ba660)
	/usr/local/go/src/runtime/proc.c:925 +0x1f fp=0x7ffeefbff778 sp=0x7ffeefbff768
runtime.malg(0x8000, 0x2ba700)
	/usr/local/go/src/runtime/proc.c:2106 +0x1f fp=0x7ffeefbff7a8 sp=0x7ffeefbff778
runtime.mpreinit(0x2baac0)
	/usr/local/go/src/runtime/os_darwin.c:137 +0x27 fp=0x7ffeefbff7c0 sp=0x7ffeefbff7a8
mcommoninit(0x2baac0)
	/usr/local/go/src/runtime/proc.c:201 +0xc9 fp=0x7ffeefbff7e8 sp=0x7ffeefbff7c0
runtime.schedinit()
	/usr/local/go/src/runtime/proc.c:138 +0x55 fp=0x7ffeefbff810 sp=0x7ffeefbff7e8
runtime.rt0_go(0x7ffeefbff848, 0x18, 0x7ffeefbff848, 0x0, 0x0, 0x18, 0x7ffeefbffa08, 0x7ffeefbffa40, 0x7ffeefbffa4c, 0x7ffeefbffa5c, ...)
	/usr/local/go/src/runtime/asm_amd64.s:95 +0x116 fp=0x7ffeefbff818 sp=0x7ffeefbff810
arduino-builder returned 2

Error compiling for board LaunchPad w/ msp432 EMT (48MHz).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by rei-vilo** [comment]
Linked to #983 ?
