### ISSUE TITLE
About the  clear() function 

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#1021]
Shouldn't the `clear()` function be simply

```
void LCD_SharpBoosterPack_SPI::clear()
{
    clearBuffer();
    flush();
}
```

instead of 
https://github.com/energia/Energia/blob/024a8fe8728a6e5af4e57832e36c0be43716f841/libraries/LCD_SharpBoosterPack_SPI/LCD_SharpBoosterPack_SPI.cpp#L178-L205

as `clearBuffer()` takes the reverse mode into account.

**Comment by StefanSch** [comment]
You are right, has the same result but much easier and less code.
(Will put this into the code with all other updates.)

Thanks!
