### ISSUE TITLE
MSP432E Missing Repository

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#1022]
The repository for the **MSP432E Ethernet** boards package is available on the Energia IDE but the source code is missing from the [GitHub Energia repository](https://github.com/energia).

<img width="800" alt="capture 2018-10-20 a 19 00 05" src="https://user-images.githubusercontent.com/951776/47258412-13ae2780-d49b-11e8-8251-d1816f1d870b.png">

**Comment by robertinant** [comment]
https://github.com/energia/msp432e-core
