### ISSUE TITLE
MSP432E — undefined reference to `asm`

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#1023]
Calling raises an error during the linking phase: undefined reference to `asm`.

> Linking everything together...
> "/Users/ReiVilo/Library/Energia15/packages/energia/tools/arm-none-eabi-gcc/6.3.1-20170620/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mthumb -nostartfiles -O0 -Wl,--gc-sections -specs=nano.specs  -specs=rdimon.specs -specs=nosys.specs "-Wl,-u,main" "-Wl,-Map,/var/folders/px/cyfvtr757lqg0yp_cv9j79jh0000gn/T/arduino_build_379144/sketch_oct20d.ino.map" -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs -o "/var/folders/px/cyfvtr757lqg0yp_cv9j79jh0000gn/T/arduino_build_379144/sketch_oct20d.ino.elf" "/var/folders/px/cyfvtr757lqg0yp_cv9j79jh0000gn/T/arduino_build_379144/sketch/main.cpp.o" "/var/folders/px/cyfvtr757lqg0yp_cv9j79jh0000gn/T/arduino_build_379144/sketch/sketch_oct20d.ino.cpp.o" "/var/folders/px/cyfvtr757lqg0yp_cv9j79jh0000gn/T/arduino_build_379144/core/Board_init.c.o" "/var/folders/px/cyfvtr757lqg0yp_cv9j79jh0000gn/T/arduino_build_379144/core/pins.c.o" "/var/folders/px/cyfvtr757lqg0yp_cv9j79jh0000gn/T/arduino_build_379144/core/package/package_ti.runtime.wiring.msp432e.variants.MSP_EXP432E401Y.c.o" "/var/folders/px/cyfvtr757lqg0yp_cv9j79jh0000gn/T/arduino_build_379144/core/SerialObjects.cpp.o" "/var/folders/px/cyfvtr757lqg0yp_cv9j79jh0000gn/T/arduino_build_379144/core/SpiObjects.cpp.o" "/var/folders/px/cyfvtr757lqg0yp_cv9j79jh0000gn/T/arduino_build_379144/core/WireObjects.cpp.o" "-L/Users/ReiVilo/Library/Energia15/packages/energia/hardware/msp432e/5.19.0/system/kernel/tirtos/packages/gnu/targets/arm/libs/install-native/arm-none-eabi/lib/thumb/v7e-m/fpv4-sp/hard" "-L/var/folders/px/cyfvtr757lqg0yp_cv9j79jh0000gn/T/arduino_build_379144" "-L/Users/ReiVilo/Library/Energia15/packages/energia/hardware/msp432e/5.19.0/cores/msp432e" "-L/Users/ReiVilo/Library/Energia15/packages/energia/hardware/msp432e/5.19.0/system/energia" "-L/Users/ReiVilo/Library/Energia15/packages/energia/hardware/msp432e/5.19.0/system/kernel" "-L/Users/ReiVilo/Library/Energia15/packages/energia/hardware/msp432e/5.19.0/system/source" "-L/Users/ReiVilo/Library/Energia15/packages/energia/hardware/msp432e/5.19.0/system/kernel/tirtos/builds/MSP_EXP432E401Y/energia/" "-L/Users/ReiVilo/Library/Energia15/packages/energia/hardware/msp432e/5.19.0/system/kernel/tirtos/packages" "-L/Users/ReiVilo/Library/Energia15/packages/energia/hardware/msp432e/5.19.0/cores/msp432e/ti/runtime/wiring/msp432e" "-L/Users/ReiVilo/Library/Energia15/packages/energia/hardware/msp432e/5.19.0/cores/msp432e/ti/runtime/wiring/msp432e/variants/MSP_EXP432E401Y" -Wl,--check-sections -Wl,--gc-sections "/var/folders/px/cyfvtr757lqg0yp_cv9j79jh0000gn/T/arduino_build_379144/core/core.a" "-Wl,-T/Users/ReiVilo/Library/Energia15/packages/energia/hardware/msp432e/5.19.0/system/energia/linker.cmd" "/Users/ReiVilo/Library/Energia15/packages/energia/hardware/msp432e/5.19.0/system/source/ti/devices/msp432e4/driverlib/lib/gcc/m4f/msp432e4_driverlib.a" -static -lstdc++ -lgcc -lc -lm -lnosys
> /var/folders/px/cyfvtr757lqg0yp_cv9j79jh0000gn/T/arduino_build_379144/core/core.a(wiring.c.o): In function `delayMicroseconds`:
> /Users/ReiVilo/Library/Energia15/packages/energia/hardware/msp432e/5.19.0/cores/msp432e/ti/runtime/wiring/msp432e/wiring.c:105: undefined reference to `asm`
> /Users/ReiVilo/Library/Energia15/packages/energia/hardware/msp432e/5.19.0/cores/msp432e/ti/runtime/wiring/msp432e/wiring.c:111: undefined reference to `asm`
> collect2: error: ld returned 1 exit status
> exit status 1
> Error compiling for board LaunchPad w/ msp432e EMT (120MHz).

* Minimal code

```
void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly: 
  delayMicroseconds(100);
}
``

**Comment by robertinant** [comment]
This issue was moved to energia/msp432e-core#2
