### ISSUE TITLE
MSP432E — Upload Fails

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#1024]
Uploading from Energia to the MSP432E LaunchPad fails with the following error:

> /Users/ReiVilo/Library/Energia15/packages/energia/tools/dslite/7.2.0.2096/DebugServer/bin/DSLite load -c /Users/ReiVilo/Library/Energia15/packages/energia/tools/dslite/7.2.0.2096/EK-TM4C1294XL.ccxml -f /var/folders/px/cyfvtr757lqg0yp_cv9j79jh0000gn/T/arduino_build_494389/MSP432E.ino.elf 
> DSLite version 7.2.0.2096
> Configuring Debugger (may take a few minutes on first launch)...
> 	Initializing Register Database...
> 	Initializing: CORTEX_M4_0
> 	Executing Startup Scripts: CORTEX_M4_0
> GEL: CORTEX_M4_0: GEL Output: 
> Memory Map Initialization Complete
> Connecting...
> error: CORTEX_M4_0: Error connecting to the target: Frequency is out of range.
> Failed: Operation was aborted
> the selected serial port Failed: Operation was aborted
>  does not exist or your board is not connected

<img width="759" alt="capture 2018-10-21 a 12 20 36" src="https://user-images.githubusercontent.com/951776/47265660-bdd59000-d52b-11e8-87a7-5ca4deb81eca.png">

However, using **UniFlash 4.4.0** works fine.

**Comment by robertinant** [comment]
This issue was moved to energia/msp432e-core#1
