### ISSUE TITLE
PROBLEM WITH SERIAL CONNECTION IN MAC OS CATALINA

### ISSUE THREAD

**Issue by cenkaybiyik** [energia/Energia#1047]
Dear﻿ All, 

I have a problem with my Energia IDE. I have using my Tiva c ek-tm4c123gxl board. Also I am using the Energia ide on Mac OS Catalina 10.15. But in Energia IDE in the Mac doesn't see my board. I cannot see anything except for bluetoothport in serial port place.On the other hand I don't have any problems with Arduino boards﻿ and the Arduino ide in Mac too. Help me with this problem please.Have a nice day and good luck :)﻿

**Comment by robertinant** [comment]
Please continue the discussion here in the tiva-core repo: https://github.com/energia/tivac-core/issues/44

**Comment by robertinant** [comment]
I don't see any issues either so this is not a bug. Can you please post a question in the forum here: https://forum.43oh.com/forum/125-energia-tivaccc3xxx/ so that we can follow up there:
