### ISSUE TITLE
MSP430 on Energia 1.8.10E23 — Upload fails on macOS and Windows

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#1053]
Upload fails with Energia 1.8.10E23 on macOS when targeting the MSP430G2231, MSP430G2452, MSP430G2553 and MSP430FR5739. 

Energia generates 

```
~/Library/Energia15/packages/energia/tools/mspdebug/0.24/mspdebug rf2500 --force-reset prog '/var/folders/wn/n7qqb8ss0k3bvpqwfcdwp_7r0000gn/T/arduino_build_280546/Blink.ino.hex’ 
```

and it should be 

```
~/Library/Energia15/packages/energia/tools/mspdebug/0.24/mspdebug rf2500 --force-reset 'prog /var/folders/wn/n7qqb8ss0k3bvpqwfcdwp_7r0000gn/T/arduino_build_280546/Blink.ino.hex’
```

Note the `‘` before `prog`, not after.

The problem seems to appears on Windows too, as per https://forum.43oh.com/topic/19164-upload-error-filename-syntax-is-incorrect/?do=findComment&comment=90318

**Comment by rei-vilo** [comment]
- Edit the file /Applications/Energia.app/Contents/Java/hardware/energia/msp430/platform.txt

- Change

```
tools.mspdebug.upload.pattern={cmd.path} {upload.verbose} {upload.protocol} --force-reset "prog '{build.path}/{build.project_name}.hex'"
```

for 

```
tools.mspdebug.upload.pattern={cmd.path} {upload.verbose} {upload.protocol} --force-reset 'prog "{build.path}/{build.project_name}.hex"'
```

Note the switch between single and double quotes.

I haven't tested this solution with paths that include spaces.

**Comment by StefanSch** [comment]
I see some issues on Windows with this version
Suggest to use this one:
tools.mspdebug.upload.pattern={cmd.path} {program.verbose} {protocol} --force-reset "prog {build.path}/{build.project_name}.hex"

Note: should be changed for 
tools.mspdebug.program.pattern={cmd.path} {upload.verbose} {upload.protocol} --force-reset "prog {build.path}/{build.project_name}.hex"

as well.

Note : removed the ' and only use "
Can you check if this is working for OSX as well?

**Comment by rei-vilo** [comment]
`tools.mspdebug.program.pattern={cmd.path} {program.verbose} {protocol} --force-reset "prog {build.path}/{build.project_name}.hex"` works for me on macOS.

I guess the second level of quotes was prompted by paths with spaces.

**Comment by StefanSch** [comment]
yes, i also think this was the intention.
Just commited the fix.
