### ISSUE TITLE
undefined reference to `log'

### ISSUE THREAD

**Issue by VenomXNL** [energia/Energia#110]
The math.h function 'log' doesn't seem to work in Energia,
is this a known problem or is it just not supported by Energia?

I created an log calculation but when i compiled i received an error:
undefined reference to `log'
collect2: ld returned 1 exit status

I know that in a 'normal' C environment i could solve this problem by adding  -lm
to the compiler command line, because of these functions are not implemented in libc.

But i could not find any way to add the -lm option to the command line.
I've tried searching on the net for answers and tried several options in Energia,
I've even tried to add  -lm to the Energia command-line (just a guess) but no luck.

Is this an no-support issue or a bug? because the syntax-highlighting DOES respond to log,
i also realize that this could be the result of the port from the Arduino software (the syntax). 

Maybe it is an option to add compiler settings/command-line options to the Energia.

**Comment by Ashok0410** [comment]
here i am also getting same problem in Energia, when i am trying to compile my code i got following errors


Energia: 1.6.10E18 (Linux), Board: "CC3200-LAUNCHXL (80MHz)"

sketch/SX_01a_TX_LoRa.pde.cpp.o: In function `setup':
/home/quantum/Energia/libraries/LLOra/arduinoLoRa/examples/SX_01a_TX_LoRa/SX_01a_TX_LoRa.pde:52: undefined reference to `SX1272::ON()'
/home/quantum/Energia/libraries/LLOra/arduinoLoRa/examples/SX_01a_TX_LoRa/SX_01a_TX_LoRa.pde:57: undefined reference to `SX1272::setMode(unsigned char)'
/home/quantum/Energia/libraries/LLOra/arduinoLoRa/examples/SX_01a_TX_LoRa/SX_01a_TX_LoRa.pde:62: undefined reference to `SX1272::setHeaderON()'
/home/quantum/Energia/libraries/LLOra/arduinoLoRa/examples/SX_01a_TX_LoRa/SX_01a_TX_LoRa.pde:67: undefined reference to `SX1272::setChannel(unsigned long)'
/home/quantum/Energia/libraries/LLOra/arduinoLoRa/examples/SX_01a_TX_LoRa/SX_01a_TX_LoRa.pde:72: undefined reference to `SX1272::setCRC_ON()'
/home/quantum/Energia/libraries/LLOra/arduinoLoRa/examples/SX_01a_TX_LoRa/SX_01a_TX_LoRa.pde:77: undefined reference to `SX1272::setPower(char)'
/home/quantum/Energia/libraries/LLOra/arduinoLoRa/examples/SX_01a_TX_LoRa/SX_01a_TX_LoRa.pde:82: undefined reference to `SX1272::setNodeAddress(unsigned char)'
/home/quantum/Energia/libraries/LLOra/arduinoLoRa/examples/SX_01a_TX_LoRa/SX_01a_TX_LoRa.pde:91: undefined reference to `sx1272'
sketch/SX_01a_TX_LoRa.pde.cpp.o: In function `loop':
/home/quantum/Energia/libraries/LLOra/arduinoLoRa/examples/SX_01a_TX_LoRa/SX_01a_TX_LoRa.pde:96: undefined reference to `SX1272::sendPacketTimeout(unsigned char, char*)'
/home/quantum/Energia/libraries/LLOra/arduinoLoRa/examples/SX_01a_TX_LoRa/SX_01a_TX_LoRa.pde:103: undefined reference to `SX1272::sendPacketTimeout(unsigned char, char*)'
/home/quantum/Energia/libraries/LLOra/arduinoLoRa/examples/SX_01a_TX_LoRa/SX_01a_TX_LoRa.pde:108: undefined reference to `sx1272'
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board CC3200-LAUNCHXL (80MHz).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by aggarwalvinayak** [comment]
I think it has not been solved completely... I still faced this problem of ```/tmp/ccJ4nZFW.o: In function `main':
abc.c:(.text+0x2a): undefined reference to `log2'
collect2: error: ld returned 1 exit status```
just a simple test program and copied it from net to check how the`log` function works
http://p.ip.fi/OGgU this is the sample program i wrote..
