### ISSUE TITLE
delayMicroseconds on Stellaris LaunchPad

### ISSUE THREAD

**Issue by Dresch123** [energia/Energia#154]
Sorry if this is not the right place to query about possible bugs. When using Energia with the Stellaris LaunchPad, this code produces no delay:
unsigned int utime = 65530;
  delayMicroseconds(utime);              
  delayMicroseconds(utime);
  delayMicroseconds(utime);             
  delayMicroseconds(utime);
  delayMicroseconds(utime);              
  delayMicroseconds(utime);
  delayMicroseconds(utime);              
  delayMicroseconds(utime);
  delayMicroseconds(utime);             
  delayMicroseconds(utime);  
but this does
delay(655);
Has delayMicroseconds been implemented yet?
Thanks! (I am really enjoying the Energia platform.)

**Comment by robertinant** [comment]
This has been fixed with commit 9f7447641f9bc2e04ba6781618a05a8c9b30c681
