### ISSUE TITLE
Hardware UART declaration

### ISSUE THREAD

**Issue by cosmok82** [energia/Energia#165]
Hi, I want to use the hardware serial on Stellaris Launchpad (the orange ones on schematic). I declared them with this implementation

HardwareSerial com;

void setup() {
  // select the UART port (1-7):
  com.selectModule(6);
  // initialize serial communications at 9600 bps:
  com.begin(9600);
}

I tried it with all ports from 1 to 7, excluded port 0 and 6; but don't work.
Do you have a solution?

**Comment by PrashantDandriyal** [comment]
The same issue seems to trouble me while interfacing EK-TM4C123GXL  with bluetooth modules like HC05 and HM-10. The issue seems to arise in the UART communication.
I didn't find any Issue on GitHub.
Please Help.
