### ISSUE TITLE
Very slow on Ubuntu 12.10 64-bit

### ISSUE THREAD

**Issue by Fraoch808** [energia/Energia#207]
I installed two versions of Energia that were modified to run on Ubuntu 12.10 64-bit:

http://elabz.com/msp430-in-64-bit-ubuntu-12-04-linux-the-arduino-way/

and

https://github.com/energia/Energia/issues/98#issuecomment-9868124

Although Energia (eventually) gets up and running, it is extremely slow with both versions.  Each menu item takes 15 seconds to appear and the entire program acts like it wants to hang or freeze at any moment.  Sometimes it does, freezing the entire Ubuntu system.

CPU and memory usage isn't high when it's running.

My system should be powerful enough:

AMD Phenom II x4, 4 GB RAM

java version "1.7.0_15"
OpenJDK Runtime Environment (IcedTea7 2.3.7) (7u15-2.3.7-0ubuntu1~12.10)
OpenJDK 64-Bit Server VM (build 23.7-b01, mixed mode)

Any ideas?

**Comment by robertinant** [comment]
Energia 18 uses a new java serial library that seems to have improved things. Unfortunately there is little I can do about still existing slowness. It's how the emulator behaves on the MSP430G2 LaunchPad.
