### ISSUE TITLE
Download problems from energia.nu website

### ISSUE THREAD

**Issue by pbrier** [energia/Energia#233]
I get reports (and confirmed from several locations and browsers) that downloading from energia.nu does not always work.

The URL "http://energia.nu/download/download.php?file=energia-0101E0009-windows.zip"

Stalls at about 8MB consistently from some locations. From other locations it works OK.
Could be some (transparent) proxy in the line that messes things up, or the HTTP server?
Where is it hosted?  

Anyone else with problems?

**Comment by Basilisvirus** [comment]
> The URL "http://energia.nu/download/download.php?file=energia-0101E0009-windows.zip"

this url does not exist anymore.

I am trying to download the TivaC Boards  from Greece (I believe is this link http://s3.amazonaws.com/energiaUS/tools/windows/gcc-arm-none-eabi-6.3.1-20170620-windows.tar.bz2) and it downloads with a speed of  -based on the energia UI - 10kb (this is bits or Bytes?) pes second:

![image](https://user-images.githubusercontent.com/18421898/201043689-b9da0602-324b-4cf9-8108-e861f396dff3.png)

And it stucks at some point... I have been trying to download it 2 days now. Is there any instruction set on how to install the boards manually? I have managed to download this file via browser. But I also do not know if it is the only file I need.

**Comment by rei-vilo** [comment]
I am afraid Energia is no longer maintained.

**Comment by rei-vilo** [comment]
I would suggest asking Texas Instruments for help at https://e2e.ti.com/.

The TivaC was deprecated when the MSP432 was launched, and then promoted again when the MSP432 was killed (see https://github.com/energia/msp432r-core/issues/40).

I was involved in the Energia project, but it is terminated now. I am no longer using the LaunchPad boards.

**Comment by Andy4495** [comment]
While Energia is no longer maintained, the existing board packages (MSP430, MSP432, Tiva, etc) can be loaded with Arduino. So you can continue to develop with the LaunchPad boards using Arduino software. See https://github.com/Andy4495/TI_Platform_Cores_For_Arduino.
