### ISSUE TITLE
Serial1 on LaunchPad Stellaris: UART(1) is active on PC_4 / PC_5 but not on PB_0 / PB_1

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#278]
**UART(1) is active on PC_4 / PC_5 but not on PB_0 / PB_1.**

The Stellaris® LM4F120H5QR Microcontroller Datasheet (lm4f120h5qr) mentions those  pins, for example on tables 21-5 and 21-6, consistent with the pins map I've released.

But why the pins aren't defined on HardwareSerial.cpp?

```
//*****************************************************************************
//
// The list of UART GPIO configurations.
//
//*****************************************************************************
static const unsigned long g_ulUARTConfig[8][2] =
{
    {GPIO_PA0_U0RX, GPIO_PA1_U0TX}, {GPIO_PC4_U1RX, GPIO_PC5_U1TX},
    {GPIO_PD6_U2RX, GPIO_PD7_U2TX}, {GPIO_PC6_U3RX, GPIO_PC7_U3TX},
    {GPIO_PC4_U4RX, GPIO_PC5_U4TX}, {GPIO_PE4_U5RX, GPIO_PE5_U5TX},
    {GPIO_PD4_U6RX, GPIO_PD5_U6TX}, {GPIO_PE0_U7RX, GPIO_PE1_U7TX}
};
```

Is there a reason?

![capture decran 2013-10-19 a 22 13 15](https://f.cloud.github.com/assets/951776/1367275/ca3e5a28-3910-11e3-84f5-7dc491b29755.png)
![capture decran 2013-10-19 a 22 13 04](https://f.cloud.github.com/assets/951776/1367276/ca409e8c-3910-11e3-9912-e4dc8903748c.png)
![capture decran 2013-10-19 a 22 16 12](https://f.cloud.github.com/assets/951776/1367277/ca48cb2a-3910-11e3-843f-cc987b853f58.png)
![capture decran 2013-10-19 a 22 16 00](https://f.cloud.github.com/assets/951776/1367278/ca4d7d6e-3910-11e3-9855-696cd40555bc.png)

**Comment by spirilis** [comment]
Closing this in lieu of issue #552 with pullrequest
