### ISSUE TITLE
WiFi.startSmartConfig() does not work for TivaC

### ISSUE THREAD

**Issue by robertinant** [energia/Energia#311]
Code hangs in int WiFiClass::startSmartConfig().
Changing the delay in
while (ulCC3000Connected == 1)
{
    delay(500)
}

To a delay of 20 sec seems to work around the issue.

**Comment by robertinant** [comment]
This applied to the CC3000. Support for the CC3000 BoosterPack has been discontinued.

**Comment by adrianF-TI** [comment]
Hey Robert

Can you confirm if this is specific to TM4C? I am able to get SmartConfig working on both CC3200 and I believe I’ve got it working on MSP432 + CC3100 (but it’s a bit flakey)

Adrian

From: robertinant
Reply-To: energia/Energia
Date: Thursday, September 24, 2015 at 1:04 PM
To: energia/Energia
Subject: Re: [Energia] WiFi.startSmartConfig() does not work for TivaC (#311)


Closed #311<https://github.com/energia/Energia/issues/311>.
