### ISSUE TITLE
TivaPad — MCU Names Possible Conflict

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#324]
For the LaunchPad Tiva C Series, there is a potential conflict between names used for identifying the MCU:
- `TM4C123GH6PM`
- `TM4C1233H6PM`

including related derived variables as `PART_TM4C1233H6PM` `PART_TM4C123GH6PM`

If confirmed, update the label from **Question** to **Bug**

**Comment by robertinant** [comment]
This issue was moved to energia/tivac-core#31
