### ISSUE TITLE
LIBUSB_ERROR_NOT_SUPPORTED

### ISSUE THREAD

**Issue by varnonga** [energia/Energia#334]
Well, I am new to Enegia. So, I got the new updated software zip file, downloaded it, unzipped it and stuck into a project directory.

I also have the TivaC launch pad printed circuit board. Not knowing how to set up Energia, I simply thumb through the the first directory (energia-0101E0011) and clicked on the Energia executable.

I plugged in my board into the USB port. I immediatly tried loading a driver but for some reason, it could not find it. So I tried to open up energia and go to the Blink example. It compiled but when I tried down loading it, I got an ICDI usb device error. I mitigated this by down loading the stellaris_icdi_drivers. Once I did that and replugged in the TivaC launchpad, my windows XP operating system downloaded the driver and all was now working.

So, I reopened Energia again. Again I went to the example "Blink". Again everything compiled correctly. I tried down loading it and I got the following error:

LIBUSB_ERROR_NOT_SUPPORTED

**Comment by robertinant** [comment]
This issue was moved to energia/tivac-core#29
