### ISSUE TITLE
analogWrite bug

### ISSUE THREAD

**Issue by Rob-Bugel** [energia/Energia#335]
Hi folks,

I was trying to use PWM on pin PB_2  on a launchpad tiva with Eneriga but my program crashed, after some searching i found out there is a bug in enableTimerPeriph() in the file wiring_analog.c: for the normal timers Timer0 ... Timer5 the address is incremented by 1
and not with the shift (as in line 79 of the file). 
so instead of    ROM_SysCtlPeripheralEnable((SYSCTL_PERIPH_TIMER0 - 1) + (1 << offset));
it should be      ROM_SysCtlPeripheralEnable(SYSCTL_PERIPH_TIMER0 + offset);
now my pin behaves as expected.
thanks for making Energia,

greetings Rob Bugel

**Comment by robertinant** [comment]
This was fixed in commit 3054cac51743899c67fd5abcd0fb8899583ccc5c
