### ISSUE TITLE
Implement I²C Clock Stretching on the Stellaris / Tiva C

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#336]
The I²C specifications ([NXP](http://www.nxp.com/documents/other/UM10204_v5.pdf), [I²C-bus.org](http://www.i2c-bus.org/clock-stretching/)) allow the slave to set the SCL clock line low to make the master wait. This is called clock streching.

> An I2C slave is allowed to hold down the clock if it needs to reduce the bus speed. The master on the other hand is required to read back the clock signal after releasing it to high state and wait until the line has actually gone high.

How to implement clock stretching on the Stellaris LM4F120 / Tiva C TM4C123?

For example, the `twi.h` library for the MSP430 includes two functions that are used this purpose: 

```
void twi_stop(void);
void twi_releaseBus(void);
```

Thank you!

**Comment by robertinant** [comment]
This issue was moved to energia/tivac-core#28
