### ISSUE TITLE
Add Basic Multithreading for TM4C123 / TM4C129 / CC3200

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#348]
The power of the new Connected LaunchPad makes more complex projects possible.

One limitation with the Wiring / Arduino framework is only one main `loop()` run. The idea would be to incorporate some sort of multithreading, without making competition to TI RTOS.

As an example, see the crude implementation in Arduino with the [Scheduler library](http://arduino.cc/en/Reference/Scheduler). It only allows adding threads, but without any control -no semaphore, no mutex.

**Comment by murix** [comment]
@spirilis @rei-vilo @udif  can TI-RTOS integrated in Energia without licensing problems?
I think migrate from FreeTOS to TI-RTOS and re submit pull request #522

**Comment by rei-vilo** [comment]
Licence-related questions are handled by @robertinant and TI.

**Comment by spirilis** [comment]
Fwiw I'm fairly sure the answer is yes but a TI'er should chime in.

**Comment by robertinant** [comment]
@murix can you please send me an e-mail at make <at> energia.nu so we can get a discussion started?

**Comment by karthigat** [comment]
how to port freeRTOS in energia. Do energia supports freeRTOS?

**Comment by spirilis** [comment]
Energia does not have any specific support for FreeRTOS.  In theory it might not be hard to bolt FreeRTOS on top of the core framework, but I don't know of anyone trying that.  Energia's moving to employ TI-RTOS in new platforms (in part because newer TI chips basically require the use of TI-RTOS for supportability sake).

**Comment by karthigat** [comment]
ok thanxs...
How to assign task in energia? everything is build in..?
