### ISSUE TITLE
Implement SPI Slave on Energia

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#378]
Implement SPI slave mode for the LM4F TM4C LaunchPads, leveraging the StellarisWare TivaWare.

**Comment by sgang007** [comment]
Yes... SPI Slave is needed in the launchpads

**Comment by ncw2k69** [comment]
hi all,
any news about SPI Slave on LM4F120?
i found in the library that i set the CS as INPUT, SPI will switch to slave mode. this will work? is somewhere an example for spi slave mode and attach interrupt? 
sorry... i'm new to this board, i just used arduino till now.
thank you
have a great day!

**Comment by robertinant** [comment]
This issue was moved to energia/tivac-core#21
