### ISSUE TITLE
CC3000 SmartConfig  does not work with TM4C123GXL  

### ISSUE THREAD

**Issue by robertinant** [energia/Energia#388]
SmartConfig hangs on TM4C LaunchPad and Connected LaunchPad.

**Comment by josedilone** [comment]
So if it doesn't work with TM4C how should i connect my cc3000 module with my tiva c TM4c123g? i need a way as soon as possible please

**Comment by rei-vilo** [comment]
As per #311,

> This applied to the CC3000. Support for the CC3000 BoosterPack has been discontinued.
