### ISSUE TITLE
CC3200: Improved SimpleWebServerWiFi Example

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#434]
On the **SimpleWebServerWiFi** example, replace

```
// the content of the HTTP response follows the header:
client.print("Click <a href=\"/H\">here</a> turn the RED LED on<br>");
client.print("Click <a href=\"/L\">here</a> turn the RED LED off<br>");
```

by

```
// the content of the HTTP response follows the header:
client.println("<html><head><title>Energia CC3200 WiFi Web Server</title></head><body align=center>");
client.println("<h1 align=center><font color=\"red\">Welcome to the CC3200 WiFi Web Server</font></h1>");
client.print("RED LED <button onclick=\"location.href='/H'\">HIGH</button>");
client.println(" <button onclick=\"location.href='/L'\">LOW</button><br>");
```

for nicer looking page and button.

![capture 2014-08-14 a 19 52 03](https://cloud.githubusercontent.com/assets/951776/3924288/c058825c-23db-11e4-8b20-4989c47586d4.png)

**Comment by neilwang0913** [comment]
I have use the Energia 14 version to do the three LED control and face the same problem as  mckargaci commented on Dec 9 2014. Is there some solution for this problem?

**Comment by spirilis** [comment]
@neilwang0913 Not sure, but there's another quirk/bug I have a fix for (not yet merged into Energia's master tree) here - https://github.com/energia/Energia/pull/545
