### ISSUE TITLE
CC3200 Incorrect binary sketch size reported

### ISSUE THREAD

**Issue by astuder** [energia/Energia#443]
Energia for CC3200 reports an incorrect binary sketch size. E.g. for Blink:

CC3200: Binary sketch size: 102,471 bytes (of a 262,144 byte maximum)
Tiva: Binary sketch size: 4,556 bytes (of a 262,144 byte maximum)

Reported upload size is about 100K less, i.e. probably correct.

No functional impact, but might create an issue for a large sketch if Energia verifies against maximum.

**Comment by robertinant** [comment]
This has been fixed.
