### ISSUE TITLE
Energia on Mac OSX use c2000 build blink error

### ISSUE THREAD

**Issue by Honjoy** [energia/Energia#448]
[/Users/abcd/Applications/Energia.app/Contents/Resources/Java/hardware/tools/c2000/bin/cl2000, -v28, -ml, -mt, -g, --include_path="/Users/abcd/Applications/Energia.app/Contents/Resources/Java/hardware/c2000/cores/c2000", --include_path="/Users/abcd/Applications/Energia.app/Contents/Resources/Java/hardware/c2000/variants/launchpad", --include_path="/Users/abcd/Applications/Energia.app/Contents/Resources/Java/hardware/c2000/../tools/c2000/include", --gcc, --define=ENERGIA=13, --define=F_CPU=60000000L, --define=ARDUINO=101, --diag_warning=225, --display_error_number, --diag_wrap=off, --preproc_with_compile, --preproc_dependency="/var/folders/bj/ndrmnp_n377gwz8ghrf83pbh0000gn/T/build5199468965061226555.tmp/Blink.pp", "/var/folders/bj/ndrmnp_n377gwz8ghrf83pbh0000gn/T/build5199468965061226555.tmp/Blink.cpp", --output_file=/var/folders/bj/ndrmnp_n377gwz8ghrf83pbh0000gn/T/build5199468965061226555.tmp/Blink.cpp.o]

Command-line error #1965: cannot open preprocessing output file ""Blink.pp""
1 catastrophic error detected in the compilation of ""Blink.cpp"".
Compilation terminated.
>> Compilation failure

**Comment by rei-vilo** [comment]
Fix now. See #575.
