### ISSUE TITLE
LCD_SharpBoosterPack_SPI // Make this MCU agnostic

### ISSUE THREAD

**Issue by adrianF-TI** [energia/Energia#459]
https://github.com/energia/Energia/tree/master/hardware/msp430/libraries/LCD_SharpBoosterPack_SPI

This library should be MCU agnostic. Currently, there is an ifdef that has to go down to the metal for SPI initialization as well as a few MSP-specific intrinsics for delaying cycles. Is it possible to leverage a more generic SPI.begin function to enable cross compatibility? Or if necessary, perhaps add more conditions to the ifdef for additional platforms. In my particular instance, I'd love to get this library compiling for the CC3200 WiFi LaunchPad!

**Comment by robertinant** [comment]
LCD_SharpBoosterPack_SPI now works on MSP430, MSP432(MT), TIVAC and CC3200(MT)
