### ISSUE TITLE
F5529 on Mac OS X: Blink Sketch Upload Fails and Programmer Update Doesn't Fix

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#460]
On Mac OS X, Blink sketch fails to upload.

![capture 2014-08-28 a 18 45 00](https://cloud.githubusercontent.com/assets/951776/4079201/c80a389a-2ed2-11e4-84c4-ec36a32d90ce.png)

Updating the programmer doesn't fix the issue.

>
MSPDebug version 0.20 - debugging tool for MSP430 MCUs
Copyright (C) 2009-2012 Daniel Beer <dlbeer@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
>
MSP430_GetNumberOfUsbIfs
MSP430_GetNameOfUsbIf
Found FET: usbmodem14121
MSP430_Initialize: usbmodem14121
version: 4294967295
Firmware version is -1
MSP430_VCC: 3000 mV
MSP430_OpenDevice
MSP430_GetFoundDevice
Device:  (id = 0x0000)
0 breakpoints available
MSP430_EEM_Init
Chip ID data: 06 01
MSP430_Run
MSP430_Close
>

**Comment by robertinant** [comment]
This has been fixed with moving to DSLite as the programmer. Update of the programmer now happens automatically.
