### ISSUE TITLE
CC3200 PIns Not mapping correctly.

### ISSUE THREAD

**Issue by kingofl337** [energia/Energia#473]
Version: 0101E0013

When I try the example for digital push button SW2.
If I print the definition of PUSH2 = 11
If I print the definition of PIN_15 = 14

If I read pin 15 I get no response, but if I read PUSH2 it works.
Also if I analogRead(PIN58) I get 0, if I call analogRead(2) I get analog numbers.

**Comment by vinigajjar** [comment]
As suggested above to use the pin numbers mention in the above link , I used 
pinMode(3, OUTPUT);
&
digitalWrite(3,HIGH);
this made pin 3 of port 1 high

PROBLEM:
when replacing 3 with 8 in pinmode and digital write function ,it does not make pin 8 high ! and like that many more . 
in case of pin 4 we should use 'PUSH1', but what about pin 8?

**Comment by robertinant** [comment]
You might be looking at pin numbering incorrectly. Please see the pin numbering here: http://energia.nu/wordpress/wp-content/uploads/2014/06/LaunchPads-CC3200-%E2%80%94-Pins-Maps-12-28.jpeg

I just tested pin 8 as well as quite a few of the other pins and all work correctly.
