### ISSUE TITLE
CC3200 - analog read examples do not work - define analog input pins A0, A1, etc

### ISSUE THREAD

**Issue by ecdr** [energia/Energia#483]
The examples that use analog input do not work on CC3200.
For instance Examples - Analog - AnalogInput

Fails because the Arduino style names for the analog input pins (A0, A1, etc.) are not defined.

Suggest add to hardware/cc3200/variants/launchpad/pins_energia.h
(up near where RED_LED, etc. are defined)

static const uint8_t A0 = PIN_57;
static const uint8_t A1 = PIN_58;
static const uint8_t A2 = PIN_59;
static const uint8_t A3 = PIN_60;

(Or possibly in a different order, e.g. put them in order by Energia pin number 
A0 = PIN_58, A1 = PIN_59, A3 = PIN_57 and A4 = PIN_60)

Of course the CC3200 documentation sometimes refers to the I/O ports by names A0, A1.
However those names are not used in Energia, so this should not cause conflicts.
(Could make the ports PA0, PA1, similar to on Tiva LP.)

Thanks.

**Comment by Lwangaman** [comment]
White in black in the pins map shows pin 12 (in the P2 column) as a digital pin (green code = digitalRead + digitalWrite). However pinMode(12, OUTPUT) + digitalWrite(12, HIGH) does not turn on a  LED on pin 12 (P55 on the board). Pins 2-11 work just fine, I can turn on a LED with each of these, but no other numbers from 12 on seem to work. And yet, according to the pin scheme, there is a green code next to pins 12, 14, 15, 17, 18, 19, 23, 24, 27, 28, 30, and 32. Shouldn't I be able to digitalRead / digitalWrite on each of these pins too?

**Comment by Lwangaman** [comment]
I correct my previous remark, I now understand the pin 12 is used by FTDI so you have to move the jumper on J7 down one pin in order to be able to use pin 12. But I see that all other digital pins are working just fine (2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 14, 15, 17, 18, 19, 23, 24, 27, 28, 30, 31, 32).

**Comment by rei-vilo** [comment]
Yes, pins in faded colours like `13` `25` `26` `33` `34` `35` `36` `37` `38` `39` `40` mean they are not available or they are optional. Most of them are already used.
