### ISSUE TITLE
I2C Wire Library not working with G2553 LP

### ISSUE THREAD

**Issue by mringwal** [energia/Energia#486]
I don't see anything happen on pins 9/10 (p2.1/p2.2) or 14/15 (p1.6/p1.7) when running the master_write example from the Wire library.

Same example with the 5529LP has a working I2C on 14/15 (p3.0/p3.1).

It would be great, if the details of the Wire lib (it's not on the 9/10 as shown on the Booster Pack docu) could be added somewhere.

(I've connected a Logic16 to check the output)

**Comment by martin43211** [comment]
Hey guys,
sorry to warm up this post again but I experience a problem with the I2C device addresses  ALTHOUGH I took the jumper from Pin 1.6 to the LED out. I connected a GY-521 gyrosensor to Pin1.6 (SCA) and Pin1.7 (SCL). Pin AD0 is going to GND. VCC to VCC. I use the I2C scanner code from: http://playground.arduino.cc/Main/I2cScanner

I get this output in the Serial Monitor:
 Scanning...Found Address 0x01, 
Scanning...
I2C device found at address 0x01  !
I2C device found at address 0x02  !
I2C device found at address 0x03  !
I2C device found at address 0x04  !
I2C device found at address 0x05  !
I2C device found at address 0x06  !
I2C device found at address 0x07  !
I2C device found at address 0x08  !
I2C device found at address 0x09  !
I2C device found at address 0x0A  !
I2C device found at address 0x0B  !
I2C device found at address 0x0C  !
I2C device found at address 0x0D  !
I2C device found at address 0x0E  !
I2C device found at address 0x0F  !
I2C device found at address 0x10  !
I2C device found at address 0x11  !
I2C device found at address 0x12  !
I2C device found at address 0x13  !
I2C device found at address 0x14  !
I2C device found at address 0x15  !
I2C device found at address 0x16  !
I2C device found at address 0x17  !
I2C device found at address 0x18  !
I2C device found at address 0x19  !
I2C device found at address 0x1A  !
I2C device found at address 0x1B  !
I2C device found at address 0x1C  !
I2C device found at address 0x1D  !
I2C device found at address 0x1E  !
I2C device found at address 0x1F  !
I2C device found at address 0x20  !
I2C device found at address 0x21  !
I2C device found at address 0x22  !
I2C device found at address 0x23  !
I2C device found at address 0x24  !
I2C device found at address 0x25  !
I2C device found at address 0x26  !
I2C device found at address 0x27  !
I2C device found at address 0x28  !
I2C device found at address 0x29  !
I2C device found at address 0x2A  !
I2C device found at address 0x2B  !
I2C device found at address 0x2C  !
I2C device found at address 0x2D  !
I2C device found at address 0x2E  !
I2C device found at address 0x2F  !
I2C device found at address 0x30  !
I2C device found at address 0x31  !
I2C device found at address 0x32  !
I2C device found at address 0x33  !
I2C device found at address 0x34  !
I2C device found at address 0x35  !
I2C device found at address 0x36  !
I2C device found at address 0x37  !
I2C device found at address 0x38  !
I2C device found at address 0x39  !
I2C device found at address 0x3A  !
I2C device found at address 0x3B  !
I2C device found at address 0x3C  !
I2C device found at address 0x3D  !
I2C device found at address 0x3E  !
I2C device found at address 0x3F  !
I2C device found at address 0x40  !
I2C device found at address 0x41  !
I2C device found at address 0x42  !
I2C device found at address 0x43  !
I2C device found at address 0x44  !
I2C device found at address 0x45  !
I2C device found at address 0x46  !
I2C device found at address 0x47  !
I2C device found at address 0x48  !
I2C device found at address 0x49  !
I2C device found at address 0x4A  !
I2C device found at address 0x4B  !
I2C device found at address 0x4C  !
I2C device found at address 0x4D  !
I2C device found at address 0x4E  !
I2C device found at address 0x4F  !
I2C device found at address 0x50  !
I2C device found at address 0x51  !
I2C device found at address 0x52  !
I2C device found at address 0x53  !
I2C device found at address 0x54  !
I2C device found at address 0x55  !
I2C device found at address 0x56  !
I2C device found at address 0x57  !
I2C device found at address 0x58  !
I2C device found at address 0x59  !
I2C device found at address 0x5A  !
I2C device found at address 0x5B  !
I2C device found at address 0x5C  !
I2C device found at address 0x5D  !
I2C device found at address 0x5E  !
I2C device found at address 0x5F  !
I2C device found at address 0x60  !
I2C device found at address 0x61  !
I2C device found at address 0x62  !
I2C device found at address 0x63  !
I2C device found at address 0x64  !
I2C device found at address 0x65  !
I2C device found at address 0x66  !
I2C device found at address 0x67  !
I2C device found at address 0x68  !
I2C device found at address 0x69  !
I2C device found at address 0x6A  !
I2C device found at address 0x6B  !
I2C device found at address 0x6C  !
I2C device found at address 0x6D  !
I2C device found at address 0x6E  !
I2C device found at address 0x6F  !
I2C device found at address 0x70  !
I2C device found at address 0x71  !
I2C device found at address 0x72  !
I2C device found at address 0x73  !
I2C device found at address 0x74  !
I2C device found at address 0x75  !
I2C device found at address 0x76  !
I2C device found at address 0x77  !
I2C device found at address 0x78  !
I2C device found at address 0x79  !
I2C device found at address 0x7A  !
I2C device found at address 0x7B  !
I2C device found at address 0x7C  !
I2C device found at address 0x7D  !
I2C device found at address 0x7E  !
done

The GY-521 has pull-up resistors on-board which I measured: The voltage from SDA-GND and SDL-GND is 3.3V. Does anybody have a suggestion how to find my mistake? 
Cheers and thanks in advance,
M

**Comment by StefanSch** [comment]
Hi,
with Energia17 the default pins for the I2C have been changed to pin 9 and 10 so that it is consistent for all Launchpads. Unfortunately the pin map picture for this Launchpad have not been updated so far.
So either connect to the pins 9 and 10 or switch to the alternate I2C bus with
  Wire.begin(0);        // join i2c bus (address optional for master)
or
  setModule(0);

**Comment by rei-vilo** [comment]
I've updated the pins map some time ago but it hasn't been published.

![launchpads msp430g2 pins maps](https://cloud.githubusercontent.com/assets/951776/14011952/cd296438-f1a2-11e5-8bcd-e93d5e723a16.jpg)

**Comment by StefanSch** [comment]
Yes, I just sent a note again and requested the update.

**Comment by martin43211** [comment]
Hi Stefan and rei-vlio, 
thanks for your fast replies and inputs. So I tried switching the SCL and SDA ports from pins 1.7 and 1.6, respectively to pins 2.1 and 2.2 and did NOT change the Wire.begin(); in the example from:
http://playground.arduino.cc/Main/I2cScanner
Then the I2C scanner gives out this:

I2C Scanner
Scanning...
Unknow error at address 0x01
Unknow error at address 0x02
Unknow error at address 0x03
Unknow error at address 0x04
Unknow error at address 0x05
Unknow error at address 0x06
Unknow error at address 0x07
Unknow error at address 0x08
Unknow error at address 0x09
Unknow error at address 0x0A
Unknow error at address 0x0B
Unknow error at address 0x0C
Unknow error at address 0x0D
Unknow error at address 0x0E
Unknow error at address 0x0F
Unknow error at address 0x10
Unknow error at address 0x11
Unknow error at address 0x12
Unknow error at address 0x13
Unknow error at address 0x14
Unknow error at address 0x15
Unknow error at address 0x16
Unknow error at address 0x17
Unknow error at address 0x18
Unknow error at address 0x19
Unknow error at address 0x1A
Unknow error at address 0x1B
Unknow error at address 0x1C
Unknow error at address 0x1D
Unknow error at address 0x1E
Unknow error at address 0x1F
Unknow error at address 0x20
Unknow error at address 0x21
Unknow error at address 0x22
Unknow error at address 0x23
Unknow error at address 0x24
Unknow error at address 0x25
Unknow error at address 0x26
Unknow error at address 0x27
Unknow error at address 0x28
Unknow error at address 0x29
Unknow error at address 0x2A
Unknow error at address 0x2B
Unknow error at address 0x2C
Unknow error at address 0x2D
Unknow error at address 0x2E
Unknow error at address 0x2F
Unknow error at address 0x30
Unknow error at address 0x31
Unknow error at address 0x32
Unknow error at address 0x33
Unknow error at address 0x34
Unknow error at address 0x35
Unknow error at address 0x36
Unknow error at address 0x37
Unknow error at address 0x38
Unknow error at address 0x39
Unknow error at address 0x3A
Unknow error at address 0x3B
Unknow error at address 0x3C
Unknow error at address 0x3D
Unknow error at address 0x3E
Unknow error at address 0x3F
Unknow error at address 0x40
Unknow error at address 0x41
Unknow error at address 0x42
Unknow error at address 0x43
Unknow error at address 0x44
Unknow error at address 0x45
Unknow error at address 0x46
Unknow error at address 0x47
Unknow error at address 0x48
Unknow error at address 0x49
Unknow error at address 0x4A
Unknow error at address 0x4B
Unknow error at address 0x4C
Unknow error at address 0x4D
Unknow error at address 0x4E
Unknow error at address 0x4F
Unknow error at address 0x50
Unknow error at address 0x51
Unknow error at address 0x52
Unknow error at address 0x53
Unknow error at address 0x54
Unknow error at address 0x55
Unknow error at address 0x56
Unknow error at address 0x57
Unknow error at address 0x58
Unknow error at address 0x59
Unknow error at address 0x5A
Unknow error at address 0x5B
Unknow error at address 0x5C
Unknow error at address 0x5D
Unknow error at address 0x5E
Unknow error at address 0x5F
Unknow error at address 0x60
Unknow error at address 0x61
Unknow error at address 0x62
Unknow error at address 0x63
Unknow error at address 0x64
Unknow error at address 0x65
Unknow error at address 0x66
Unknow error at address 0x67
Unknow error at address 0x68
Unknow error at address 0x69
Unknow error at address 0x6A
Unknow error at address 0x6B
Unknow error at address 0x6C
Unknow error at address 0x6D
Unknow error at address 0x6E
Unknow error at address 0x6F
Unknow error at address 0x70
Unknow error at address 0x71
Unknow error at address 0x72
Unknow error at address 0x73
Unknow error at address 0x74
Unknow error at address 0x75
Unknow error at address 0x76
Unknow error at address 0x77
Unknow error at address 0x78
Unknow error at address 0x79
Unknow error at address 0x7A
Unknow error at address 0x7B
Unknow error at address 0x7C
Unknow error at address 0x7D
Unknow error at address 0x7E
No I2C devices found

When I switch back to the old configuration (Pin1.7 -> SDL and Pin 1.6 -> SDA, and Jumper from Pin 1.6 to LED2 removed ) and include change the Wire.begin() to Wire.begin(0), I get the same output as in my first post:

Scanning...
I2C device found at address 0x01 !
...you get the picture. 

Do you have any other suggestions? I have a GY-521 connected to the MSP430. The AD0 pin is connected to ground (then the device should have the address 0x68) and there are pull-up resistors on-board. It perfectly works with an Arduino Uno

**Comment by martin43211** [comment]
Even if I directly ground the SCL and SDA pins, there should at least, no I2C device should be found but I still get the message, that all addresses are ocupied with I2C devices (same message as in my first post)

**Comment by simseve** [comment]
Hi Martin,
did you solve? I have same exact issue. I2C scanner works in Arduino but not on the MSP430 and behaves exactly like you described.

**Comment by martin43211** [comment]
Hi simseve,
unfortunately no. I could not figure it out. Did you try to attach the MSP to the Arduino and use the I2C scanner? I tried but the arduino does not 'see' the MSP when they are connected via I²C. Does anybody else have an idea

**Comment by simseve** [comment]
Hi,
 I just saw that Wire library folder was empty on my Mac. I'm downloading the library again.

**Comment by martin43211** [comment]
Hey, 
the Wire.h and Wire.cpp are in the MPS430/cores/ folder and I found that this should not be a problem. Moved them to MSP430/libraries/Wire and still there is no effect except that I can now add the Wire.h library in Energia via Sketch -> Import Libraries which was not possible before. 
Unfortunately I have no idea anymore and will use the Arduino for now since I just started with µCs and don't want to frustrate myself right from the start. Would be interested though if you find a solution.

**Comment by martin43211** [comment]
The only last thing I found is that, when I connect the SCL and SDA pins to GND and VCC, respectively, I get different outputs of the I2C scanner. For the connection to GND, I get:

Unknown error at address ... (a long list with all addresses)

and when I connect them both to VCC: 

I2C device found at address ... (a long list with all addresses)

**Comment by StefanSch** [comment]
Did some more test and found that this might never has worked.
Just commited a version which does support the scanning of the I2C slaves:
https://github.com/energia/Energia/pull/868/files

**Comment by StefanSch** [comment]
fix is available with pull request #868

**Comment by simseve** [comment]
Thanks StefanSch. How can I try your mods on my side (procedure to include your changes)?thanks

**Comment by StefanSch** [comment]
You can download the raw file from git hub and replace it within your energia system:
https://raw.githubusercontent.com/energia/Energia/issue_486/hardware/msp430/cores/msp430/twi.c
https://raw.githubusercontent.com/energia/Energia/issue_486/hardware/msp430/cores/msp430/twi_sw.c

They are located in this path:
.../hardware/msp430/cores/msp430

**Comment by curtis63** [comment]
I am having the same problem as above.  Just purchased a brand new Launchpad for G2 from TI.  I attached a sensor to it.  I am able to successfully communicate with the sensor and get data from it, however, when I run the scanner, I get a device found at all addresses, even though there is only a single sensor.

**Comment by rei-vilo** [comment]
Which I²C port are you using?

Default I²C port uses pins 9 and 10.

**Comment by rei-vilo** [comment]
<img width="400" alt="msp430g2553" src="https://cloud.githubusercontent.com/assets/951776/14391164/c70199ee-fdba-11e5-87f4-555f580e0c80.png">

**Comment by curtis63** [comment]
Pins 14/15. Aka P1.6/P1.7.

Unable to communicate with my sensor and get valid data however the scanner
program does not work. It shows something at every address.

**Comment by rei-vilo** [comment]
Use default port.

**Comment by curtis63** [comment]
I’ll have to check this again tonight when I get back home.  Looking at the image, it shows SCL(0) and SDA(0) on pins 14/15 and then SCL(1) and SDA(1) on pins 9/10.  What’s the (0) and the (1) mean?  So, I guess the scanner is set to work with pins 9/10 and I can use 9/10 or 14/15 for my I2C communications, but only 9/10 if I want the Scanner to work?

 

I’ll give it a try when I get home tonight.  Thanks for your help on this.

**Comment by curtis63** [comment]
Excellent !!  It does work when I use Pins 9 and 10.  I was using pins 14 and 15.

 

We have already built a circuit board based on the older spec from 2012.  It showed pins 14 and 15.   Where would I change the code to switch to pins 14 and 15 (which are shown on the image below as SCL(0) and SDA(0)

**Comment by StefanSch** [comment]
add a
  Wire.setModule(0);    // 0: indicates the bus as shown in the pin map
before the
  Wire.begin();        // join i2c bus (address optional for master)

**Comment by curtis63** [comment]
Ok, so when I call 
Wire.setModule(0); 
I get a bad side effect.  Calls to Wire.endTransmission() don't return...
I debugged into this using Code Composer Studio and the code appears to be locked up in the following section of the two_writeTo function in twi.c.  Specifically the bolded while statement below:

```
#if defined(__MSP430_HAS_USCI__) || defined(__MSP430_HAS_USCI_B0__) || defined(__MSP430_HAS_USCI_B1__)
	/* Ensure stop/start condition got sent before we exit. */
	if(sendStop)
	{
		**while (UCBxCTL1 & UCTXSTP);	// end with stop condition**
	} else {
		while (UCBxCTL1 & UCTXSTT);	// end with (re)start condition
	}
#endif
```

**Comment by curtis63** [comment]
So, my Launchpad uses a 20 pin MPS430G2553 chip.  On it, P1.6 is pin 14 and P1.7 is pin 15.  However, TI makes a 28 pin MPS430G2553 chip.  On it, P1.6 is pin 22 and P1.7 is pin 23.  
P1.4 is pin 6 and P1.5 is pin 7 on both the 20 pin and the 28 pin MPS430G2553 chip.

Is this going to cause problems using the library with Wire.setModule(0); specified?

**Comment by StefanSch** [comment]
If you go to the 28 pin device the I2C should work as well as the I2C is on the same port pins.
And this is set in the 
....\hardware\msp430\variants\launchpad\pins_energia.h
file.
But you will get a lot of issues on the other pins as the mapping of the pin assigned to the Launchpad  and the device will not map.
So you may should consider to generate a own pins_energia.h if this is required.

**Comment by curtis63** [comment]
Sounds good.  My colleague will be testing this on the 28 pin chip tomorrow.  I have heard people express concerns about the efficiency of using Energia vs standard C code when programming the MSP430G2553 controller.  They are worried about efficiency and about battery power.  What is your opinion about the pros and cons of using Energia vs standard C code ?

 

I LOVE the ease of use of the language and libraries.  Nice to have a layer of abstraction over the direct calls that standard C requires.

**Comment by StefanSch** [comment]
Thanks for the info - it always helps to get the confirmation that a fix is working.

It is a good question to ask about the pros and cons of Energia vs standard c code.
I am sure we could have a discussion over a whole evening with some beers.
... and it could also become very philosophic.....

Finally let me try go give you an answer which expresses my opinion:
If you need to have a code which is optimized to the final line of code for either execution speed or energy consumption Energia is the wrong tool.
If you would like to have a fast prototype or if you not have the time, passion and technical understanding to go down to each configuration bit of a microcontroller energia is a perfect tool.
Anything between is up to the user.
If you look for efficiency and battery power you can also with Energia build systems which are highly efficient and working for a very long time. But there are some considerations and limitations you may need to be aware of. If you ratio of active time to low power mode time is very high - means you are long time in low power modes, then you will most properly not see a big difference.
If you have to wake up very often the it depends if the wake up is mainly handled in an interrupt service routine / handler then it also depends only on your programming skills and on how you have configured the systems.
If you wake up very often and always have to go through the loop function then you can might see a higher current consumption in energia.
But keep in mind this always depends on how well you know the microcontroller and your skills to optimize your application code for the lowest power consumption base on this device and your use case.

Finally - even as i know the msp430 very well for many, many years  i am contributing to this tool as i am convinced from the easy of use, the fast way of building applications and the ecosystem of launchpads and boosterpacks where it is build around.
It makes so many things so easy..... just do it .....

**Comment by curtis63** [comment]
I really appreciate your help.  I’m a 20 year Software Engineer, but have never worked with controllers and firmware before.  This is a big learning curve, but Energia makes it MUCH easier..

 

This may not be the place for technical questions, but I’m trying to get Low Power Mode implemented and saw a couple postings where they use:

 

disableWatchDog();

 

and 

 

LPM4;

 

Both of the above statements make my code LOCK up when I attempt to use Serial or delay();

 

Do you know a good work-around for this?

 

I want to be in low power mode most of the time, and wake up when a sensor interrupts on a port.

 

Where should I look for Energia support functions for this?

**Comment by spirilis** [comment]
See sleep, sleepSeconds, suspend, and wakeup (the latter is meant for running inside ISRs).

Note you can't use Serial port I/O in low power mode, so you should Serial.flush() before using sleep/sleepSeconds/suspend.

**Comment by curtis63** [comment]
I wish I could download your brain...  Thanks so much for your help!!

**Comment by walber000** [comment]
Hello guys, I'm currently trying to use my GY-521 but I'm having this i2c problem too, the scanner either founds devices everywhere or found nothing. I already replaced the twi files from the git hub solution above, and already tried pins 9/10 and 14/15, wire.setmodule(0) and everything else =/
May anyone help me?
P.S: when I read it, it only gives 0's or -1's

**Comment by curtis63** [comment]
Did you accidentally swap SCL with SDA?  Did you add pull-up resisters?  Did you remove the LED jumper from P1.6?

The TWI files exist in more than one place. Did you replace them in all the places they exist on your machine?

Thanks,
Curtis

**Comment by SunYongshuai** [comment]
I am a lover of MSP430 launchPad! I have a problem with it. I use a MSP430G2553 as master write,and use another MSP430G2553 as slaver receiver , but slaver may receive none when writer send data to it. Where is Wrong? Thanks !Thanks!Thanks a lot!
code as follow : 

slaver receiver 

#include <Wire.h>

void setup()
{
  pinMode(2,OUTPUT);
  pinMode(14, INPUT_PULLUP); 
  pinMode(15, INPUT_PULLUP); 
  digitalWrite(2,LOW);       //pin 2 is a LED
  Wire.begin(4);                // join i2c bus with address #4
  Wire.onReceive(receiveEvent); // register event
  Serial.begin(9600);           // start serial for output
}

void loop()
{
  delay(100);
}

// function that executes whenever data is received from master
// this function is registered as an event, see setup()
void receiveEvent(int howMany)
{
  while(Wire.available()) // loop through all but the last
  {
    int x = Wire.read(); // receive byte as a int
    if(x == 1)
      digitalWrite(2 , HIGH);
    else 
      digitalWrite(2 , LOW);
      
    Serial.print("Wire!\t");
    Serial.println(x);         // print the integer
  }
}

Master Write：

#include <Wire.h>
int x = 0;

void setup()
{
  Serial.begin(9600);
  Wire.begin(); // join i2c bus (address optional for master)
  pinMode(2,OUTPUT);
  digitalWrite(2,LOW);
}

void loop()
{
  Wire.beginTransmission(4); // transmit to device #4
  Wire.write(x);              // sends one byte  
  Wire.endTransmission();    // stop transmitting
  Serial.print("Send: light is :");
  Serial.println(x);
  x++;
  if(x == 2)
     x = 0; 
  if(x == 0)
    digitalWrite(2,HIGH);
  if(x == 1)
   digitalWrite(2,LOW);
 delay(1000);
}

**Comment by buihoangan** [comment]
Many thanks to Stefansch, I struggled this problem for few days before read this topic. On launchpadg2553 just one I2C module and the default i2c pins are 9 and 10, not change to pin 14 and 15.

**Comment by AB2203** [comment]
I'm trying to use the BH1750 light sensor with the MSP430 G2553
I'm new to using the launchpad and microcontrollers.
This is the code:
#include <BH1750FVI.h> // Sensor Library
#include <Wire.h> // I2C Library
uint16_t Light_Intensity=0;
BH1750FVI LightSensor;

void setup() {
  
  Serial.begin(9600);
  LightSensor.begin();
  LightSensor.SetAddress(Device_Address_H); //Address 0x5C
  LightSensor.SetMode(Continuous_H_resolution_Mode);
  Serial.println("Running..."); 
}
  void loop() 
  {
  Light_Intensity = LightSensor.GetLightIntensity();
  Serial.print ("lux=");
  Serial.print (Light_Intensity);
  delay(1000);
  }

I cant get the sensors to work
I'm confused about giving the connections and which pins to use for SCL and SDA
Any help will be great.

**Comment by curtis63** [comment]
Use P1.7 for SDA and P1.8 for SCL.  Google the particular board you are using and you should easily find a pinout for it indicating which pins to use.  I’m not familiar with the sensor you’re trying to use, or its interface.  Just make sure you’ve got the pins of your sensor on the correct pins of the Launchpad you are using.  Again, google the board pinout and there should be several images to point you in the right direction.  

 

Hope this helps,

Curtis
