### ISSUE TITLE
TM4C129 — Only UART 0 usable on connected launchpad

### ISSUE THREAD

**Issue by coon42** [energia/Energia#490]
It is not possible using any other Hardware UART port than UART0 on the connected launchpad. Any other port will crash the launchpad.

That's how I try it for UART port 3:

HardwareSerial serialMod = HardwareSerial(3);
serialMod.begin(115200);

**Comment by rahuldeo2047** [comment]
Have we checked Serial7 rx?

**Comment by PrashantDandriyal** [comment]
How do I get the HardwareSerial library for the TM4c123gxl (based on tm4c123gh6pm) ?
