### ISSUE TITLE
Serial FLash on CC3200

### ISSUE THREAD

**Issue by aruncheela** [energia/Energia#494]
It would nice if we have library with example for Using Serial Flash on CC3200 Launchpad
Thanks,
Ali

**Comment by krishnarajnairmk** [comment]
Is the flash written, the one where Application Code is written to ( dedicated SPI flash) or an external SPI flash, i.e, not the one with dedicated Flash SPI?

**Comment by rei-vilo** [comment]
Dedicated SPI Flash for code.

**Comment by spirilis** [comment]
SLFS writes to the same external flash (external to CC3100/CC3200 die but on same board) on the dedicated Flash SPI bus as where the MCU' code lives.

**Comment by krishnarajnairmk** [comment]
Awesome..:)

**Comment by rei-vilo** [comment]
See #813 #817 #827.

**Comment by harisahmed2492** [comment]
Hi.can anyone tell me how SLFS Library access the Flash Memory?How it knows address of the memory where the code ends?I am working on OTA Update kindly help over this.

Thank you

**Comment by spirilis** [comment]
It uses the SimpleLink API.  I believe the answers to your questions are unknown by us.

**Comment by harisahmed2492** [comment]
I want to know that how can I know the the starting and ending address of the code that lives inside the Flash?
 
Thank you

**Comment by spirilis** [comment]
SLFS won't tell you that if that's what you mean.  Look at the linker map files generated by the compiler for address information.

**Comment by nkarthiga** [comment]
Can anyone help me to know how to save ID & password in SLFS for easy login for cc3200?
