### ISSUE TITLE
Plans for Energia on Java 7 or 8?

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#495]
Energy requires Java 6 on Mac OS X.10 or *Yosemite*.

Arduino already offers two releases of its IDE: one for Java 6 and another for Java 7.

![capture 2014-10-17 a 22 23 35](https://cloud.githubusercontent.com/assets/951776/4685533/acacbc18-563b-11e4-9e67-35cd1aa0344c.png)

As Java 7 or 8 is strongly recommended for security reasons, what are the plans for Energia to support Java 7?

**Comment by kevarh** [comment]
It looks like you'll need to ship a 64bit version of librxtxSerial.jnilib to enable Java 7 support on OSX. Additionally Java 7 end of life is this [April](http://www.oracle.com/technetwork/java/eol-135779.html) so Java 8 support is a must.

**Comment by rei-vilo** [comment]
See #553.
