### ISSUE TITLE
Faster SPI 

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#497]
SPI speed tops at 8 MHz while MCUs have much faster clock speeds —e.g. 80 MHz for the LM4F120 / TM4C123 and the CC3200 120 MHz for the TM4C129. 

How to get 16 MHz for SPI?

**Comment by rei-vilo** [comment]
Same feature request for the MSP432, especially with the Kentec 3.5" SPI screen.

**Comment by robertinant** [comment]
This issue was moved to energia/msp432-core#27
