### ISSUE TITLE
CC3200 FDTI extension needs to be signed to work on OSX Yosemite

### ISSUE THREAD

**Issue by Tronix117** [energia/Energia#500]
Hello,

Since OSX Yosemite, all kext must be signed otherwise they will not be loaded.

Thus `FTDIUSBSerialDriver.kext` can't be loaded, and the CC3200 board will not be detected by the system and will not appears in `/dev`.

In the meanwhile, a workaround is to disable this verification at boot.

**BE CAREFUL, IT DISABLES THE SECURITY FOR ALL KEXT AND MAKE THE SYSTEM A LITTLE BIT MORE VULNERABLE**

---

First install `cc3200_drivers_mac.dmg` normaly.

Then disable the kext signature verification at boot:

    sudo nvram boot-args="kext-dev-mode=1"

Then reboot the computer, and check the kext is loaded

    kextstat | grep FTDI

If nothing appears, the FTDI may not have been loaded automaticaly and need to be loaded manualy with:

    sudo kextload /System/Library/Extensions/FTDIUSBSerialDriver.kext

If no error message, then it means it has been successfully loaded and the device should appear as `/dev/cu.usbserial-cc3200B` and in Energia.

**Comment by jmgc** [comment]
Would it be possible to add also de c2000? Taking into account that the compiler is also available for the c2000 in TI, could be it will be feasible to use it with Energia. I have checked, and it seems that the c2000 uses also an FTDI with the 0x403 vendor id, and the 0xa6d0 product id.

By the way, I have used the yosemite driver and it works perfectly well.

**Comment by spirilis** [comment]
I would imagine @treygerman is working on that already :)

**Comment by jadonk** [comment]
Apparently people installing the BeagleBone version are breaking this fix. The patch applied to the FTDI drivers for BeagleBone is at https://github.com/beagleboard/beaglebone-getting-started/blob/master/Drivers/MacOSX/FTDI/do_patch.sh. Would be nice to get a single updated driver that works on all Mac versions and FTDI devices, including BeagleBone.

**Comment by robertinant** [comment]
@jadonk I'll update the driver with the BB VID/PID's and resign so that it woks on Yosemite. Will put it up on Energia.nu and then you can take it from there and put it where you normally keep it.

**Comment by jmgc** [comment]
@robertinant, and the c2000 one? This way I will be able to test the c2000.

Thanks in advance

**Comment by robertinant** [comment]
@jmgc @jadonk, @treygerman the driver package that includes c2000, BB and CC3200 is here: http://energia.nu/files/EnergiaFTDIDrivers2.2.18.zip
Would be great if you could give it a try.

Robert

**Comment by jmgc** [comment]
The driver package seems to work. Not I have found the issue #531.

**Comment by steffoon** [comment]
I can confirm that the http://energia.nu/files/EnergiaFTDIDrivers2.2.18.zip driver works for C2000.

**Comment by robertinant** [comment]
Thanks for letting me know that it works for you. @treygerman, @jadonk can you also confirm that the driver works for you?  Ones confirmed I will update the Energia website to point to this driver and close the issue.

**Comment by jadonk** [comment]
Looks good.

**Comment by rei-vilo** [comment]
I managed to use the driver proposed in ticket #500 on Mac OS X 10.10 Yosemite.

Upload for the C2000 runs fine up to 38400 bauds. Faster speeds end with an error.

> Unable to open establish kernel autobaud

Presently, the `115200` speed is hard-coded. 

May I suggest adding the following line to `boards.txt` and updating the Java code accordingly?

```
lptms320f28027.upload.speed=38400
```

**Comment by robertinant** [comment]
@treygerman does 115200 work on Windows?

**Comment by AshuJoshi** [comment]
The signed extension does not work for me on Yosemite - I am running 10.10

**Comment by fgtb** [comment]
Unfortunately it looks like editing the Info.plist is enough to moved the kext from signed to unsigned status. For example, the Sheevaplug reports a non-standard vendor ID that requires the Info.plist to be edited, but this then breaks the signing.

Having installed the energia kext provided above, this pases with one warning:

```
bash-3.2# kextutil /System/Library/Extensions/FTDIUSBSerialDriver.kext
Warnings: 
    Dependency lacks appropriate value for OSBundleRequired and may not be availalble during early boot: 
        com.apple.iokit.IOSerialFamily - Safe Boot
```

However adding the patch for the Sheevaplug breaks it

```
bash-3.2# kextutil /System/Library/Extensions/FTDIUSBSerialDriver.kext
Diagnostics for /System/Library/Extensions/FTDIUSBSerialDriver.kext:
Warnings: 
    Dependency lacks appropriate value for OSBundleRequired and may not be availalble during early boot: 
        com.apple.iokit.IOSerialFamily - Safe Boot

Code Signing Failure: code signature is invalid
Warnings: 
    Dependency lacks appropriate value for OSBundleRequired and may not be availalble during early boot: 
        com.apple.iokit.IOSerialFamily - Safe Boot

Untrusted kexts are not allowed
ERROR: invalid signature for com.FTDI.driver.FTDIUSBSerialDriver, will not load
```
Copying the original plist file back into place returns to signed status. I'm posting this in case anyone else runs across this type of issue.
