### ISSUE TITLE
XCC3200JR and CC3200R1M2 can not download sketch

### ISSUE THREAD

**Issue by XuGuohui** [energia/Energia#507]
Hi,

I tested my CC3200 module (which the chip is XCC3200JR) on Energia, but the IDE cannot upload sketch to it, even if I restart the module. And I replaced the XCC3200HZ with CC3200R1M2 on CC3200-LAUNCHXL Rev3.2. Then I tested it with Energia, but it also cannot upload sketch to the CC3200R1M2. Both of the chip I tested is version 1.33, but the IDE read out the version is 1.32.

**Comment by krishnarajnairmk** [comment]
@XuGuohui  Me too had the same issue. Thanks for raising this. 
@robertinant Thanks a lot, replacing those file worked perfectly!! I guess nowadays TI ships CC3200R1m2.

**Comment by musart** [comment]
@robertinant thank you for owning cc3200prog for linux/mac/windows. One question for you is that there is a way to flash www/config.html through cc3200prog?

**Comment by spirilis** [comment]
Without resorting to Windows and UniFlash, you might be able to craft a sketch involving this library - https://github.com/spirilis/SLFS - and use it to write to the serial flash's /www/config.html file.

**Comment by musart** [comment]
Thanks @spirilis. I wrote a program by using SLFS and creating a header file having hexdump of a html file via 'xxd' command. Successfully flashed www/config.html.

**Comment by robertinant** [comment]
@musart can you put the example Sketch on github or gist please? I would love to integrate it into Energia.

**Comment by spirilis** [comment]
@robertinant I can make a pull-request to add my SLFS library to the WiFi library folder BTW.  It's been tested well enough by the public by now, seems like it should fit in well.

**Comment by robertinant** [comment]
@spirilis That would be great!

**Comment by spirilis** [comment]
Boom!  See #572

**Comment by mvkgit** [comment]
Hi @robertinant 
I am using cc3200 launchpad with energia on Ubuntu 16.
Energia not able to detect the board. When trying to upload a script it gives the following error

Picked up JAVA_TOOL_OPTIONS: 
fork/exec /home/mvk/.energia15/packages/energia/tools/arm-none-eabi-gcc/4.8.4-20140725/bin/arm-none-eabi-g++: no such file or directory

I have been using Energia on windows but am new to Linux environment.

**Comment by robertinant** [comment]
Can you open a terminal and:

`ls /home/mvk/.energia15/packages/energia/tools/arm-none-eabi-gcc/4.8.4-20140725/bin/arm-none-eabi-g++`

Copy that output here. It should be there if you installed CC3200 support through the board manager.

**Comment by mvkgit** [comment]
@robertinant Sorry, haven't checked github in a while.
It gives this output

`/home/mvk/.energia15/packages/energia/tools/arm-none-eabi-gcc/4.8.4-20140725/bin/arm-none-eabi-g++`

**Comment by mvkgit** [comment]
Hi @robertinant 
Can you help me with the issue? I've been digging the Internet a lot to resolve this.
I'm able to use Energia with cc3200 on windows. The thing is I don't want to use windows.
Thanks in advance.

**Comment by robertinant** [comment]
Ok, can you open a terminal and try to execute `/home/mvk/.energia15/packages/energia/tools/arm-none-eabi-gcc/4.8.4-20140725/bin/arm-none-eabi-g++`

Just a hunch, is your Linux installation 32-bit perhaps?
Can you post the output of
`uname -a`

**Comment by mvkgit** [comment]
It gives this
 `arm-none-eabi-g++: fatal error: no input files
compilation terminated.`

`uname -a` gives 
`Linux mvk-Inspiron-5547 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by robertinant** [comment]
Ok, so it is definitely there and executable. Not sure why arduino-builder is complaining that it can not find the file.

Just to make sure is this Ubuntu Ubuntu 16.04 or 16.10?

**Comment by mvkgit** [comment]
`Release:	16.04`
Does it make a difference if board is connected or not while running 
`arm-none-eabi.....` ??
