### ISSUE TITLE
RTC Library for CC3200

### ISSUE THREAD

**Issue by aruncheela** [energia/Energia#511]
Is there a RTC Library available for CC3200?

Thanks
Arun

**Comment by rei-vilo** [comment]
Please have a look at [Date and Time Library](http://bit.ly/1MBJqiY) with 
* RTC for MSP432, CC3200 non-EMT, TM4C123 and TM4C129
* NTP for CC3200 non-EMT

**Comment by rei-vilo** [comment]
See repository at https://github.com/rei-vilo/DateTimeLibrary

Feel free to add other LaunchPads !
