### ISSUE TITLE
MSP430F5529 No Sketch Larger than 64KB?

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#515]
Sketches larger than 64KB fail to link with Energia 13.

I tag this ticket as `Question`.

When another user confirms it, I'll change the tag for `Bug`.

**Comment by robertinant** [comment]
This will be corrected when I move to the new msp430-elf-gcc compiler which is on the roadmap in a couple months.

**Comment by RickKimball** [comment]
Doesn't seem like it should be closed as it hasn't been resolved. Maybe a new label is in order.

'Will not fix at this time'

**Comment by dazhbog** [comment]
Any update/roadmap on this?
