### ISSUE TITLE
Undefined reference to vtable

### ISSUE THREAD

**Issue by LaurieY** [energia/Energia#516]
Using 0013 on Windows and board any stellaris or cc3200.  With the release I get an undefined reference to vtable but if I replace pde.jar with the one for Issue #471 The compile succeeds.
A test is LCD_protocol.ino within the library lcd_sCREEN_distribution-122beta from Rei Vilo
The failure message is 
LCD_screen_font.cpp.o: In function `LCD_screen_virtual::LCD_screen_virtual()':
LCD_screen_font.cpp:(.text._ZN18LCD_screen_virtualC2Ev[_ZN18LCD_screen_virtualC5Ev]+0x1c): undefined reference to `vtable for LCD_screen_virtual'
collect2.exe: error: ld returned 1 exit status

**Comment by robertinant** [comment]
This has been fixed a while back when we closed issue #471
