### ISSUE TITLE
CC3200 SRAM not all being used?

### ISSUE THREAD

**Issue by spirilis** [energia/Energia#517]
Question for @robertinant -
In cc3200.ld (hardware/cc3200/cores/cc3200), I noticed the available SRAM for linking is only 192KB, and it starts at 16KB into the SRAM segment:
```
MEMORY
{
    SRAM (rwx) : ORIGIN = 0x20004000, LENGTH = 0x00030000
}
```
Is it possible to expand that out to use all 256KB SRAM or is there a specific reason for this?

**Comment by spirilis** [comment]
@robertinant bump - is this still applicable?

**Comment by robertinant** [comment]
I decided not to create a new board entry for this to avoid confusion and issues resulting from selecting the wrong board. 192K ought to be enough for anybody right now. We can revisit this further down the road. 

Did I just really say that and possibly repeating history shooting myself in the foot. Quote BG in 1981 said "640K ought to be enough for anybody".

**Comment by spirilis** [comment]
Haha, yup...
Well at the very least, if someone adds their own board with 256K, would Energia build correctly against it?  Curious if anything needs updating in the core to support that (linker script?)

**Comment by robertinant** [comment]
Other than the linker script no modifications would be needed to support the 256k.

**Comment by robertinant** [comment]
If a user exclusively uses the 4.1 board, then they can just leave the current board in place and modify the linker script.
