### ISSUE TITLE
CC3200 Launchpad not detected on linux box

### ISSUE THREAD

**Issue by cjdg** [energia/Energia#521]
I have connected my cc3200 launchpad on linux (ubuntu 14.10 64 bit) and there is not any ttyACMx on /dev/ and of course i cannot program it

Greetings

**Comment by mvkgit** [comment]
Hi,
I have a similar problem. Using cc3200 with energia on Ubuntu 16.
Even after creating udev rules, I am not able to upload scripts on the board.
Just able to open energia. Nothing is showing in ports (in energia tools).
Can someone tell me what is going on here?
BTW I am pretty new to linux environment
