### ISSUE TITLE
[FR] Memory Map

### ISSUE THREAD

**Issue by darkscrap** [energia/Energia#542]
Energia is awesome. Thanks to all of you who have contributed. :-)

I was just wondering if it would be possible to show a map of the memory that will be used on the device. It would obviously be chip/board specific, but the user already selects that before compiling and downloading. Maybe it'd have to be an option that would only work after compiling the code. Maybe for starters, it could just pop up a small dialog box indicating the size of the program it just sent to the device and then a percentage?

I just know that I often wonder how much memory my current program is going to use up on my device. A simple "progress" bar would be perfectly fine, showing max memory, program size, and percent used. Parallax has made a really nice one for their BASIC Stamp Editor software. (screen cap shown below) It doesn't have to be that extensive, but it would be super nice to just have that information.

Thanks!

![capture](https://cloud.githubusercontent.com/assets/6827790/5693232/12559a9c-98c9-11e4-8a61-d5d229dcc3ea.PNG)

**Comment by spirilis** [comment]
I think this is an awfully sophisticated request for Energia to be honest.  Have you checked out the TI Code Composer Studio integration with Energia?  Maybe try importing your sketch into CCS and see if its debugger has this ability.  That's supposed to be one of its main selling points (full debugger access for Energia)
