### ISSUE TITLE
Serial monitor println encoding problem

### ISSUE THREAD

**Issue by Jhet** [energia/Energia#543]
Text supposed to be printed out with Serial.print(""); appears to be binary.
![bug_energia](https://cloud.githubusercontent.com/assets/4754244/5720427/ef2a2824-9b5e-11e4-9a51-3a78434fa8a4.PNG)

**Comment by rei-vilo** [comment]
Have you checked the baud rate? 
What is the exact `Serial.print` instruction?

**Comment by Jhet** [comment]
It's just normal print text to Serial Monitor, e.g. Serial.println("Scanning networks...");
It's from #include <SPI.h>

Okay, thanks! 115200 baud did fix it and display properly.
