### ISSUE TITLE
CC3200 with TRF7970 NFC Boosterpack

### ISSUE THREAD

**Issue by avinashchakravarthi** [energia/Energia#550]
friends i'm trying to work with CC3200 with NFC boosterpack by SPI communication.i have downloaded a file (http://www.ti.com/lit/zip/sloc297) .which is compatible with msp430g2553. since i'm not professional enough to change the headers and libraries to work with cc3200. i need help from you guys to make it compatible with cc3200.
any kind of help towards this is welcome
thanks in advance

**Comment by rei-vilo** [comment]
You'll receive more answer if you post your question at http://forum.43oh.com

**Comment by avinashchakravarthi** [comment]
thanks @rei-vilo
