### ISSUE TITLE
LCD 5110 for CC3200

### ISSUE THREAD

**Issue by wayfarerbasta** [energia/Energia#563]
I am looking for a LCD library supporting the CC3200 Board. With the provided LCD_5110.cpp I get the following compile error:
\cc3200\libraries\LCD_5110\LCD_5110.cpp:46:2: error: #error Platform not supported
 #error Platform not supported

Can anybody help me and give some advices how to adapt the files for CC3200.

wayfarerbasta

**Comment by rei-vilo** [comment]
I've updated the examples with pins numbers instead of pins names.

Feel free to select your own pins to connect the Nokia 5110 LCD.

I suggest you try LCD_5110_SPI for better performance.
