### ISSUE TITLE
how to downlaod a file stored in Serial flash of cc3200

### ISSUE THREAD

**Issue by AishwaryaArun** [energia/Energia#565]
The cc3200 launchpad is made a webserver and It continuously reads some sensor data and stores it to the file- 'myfile.csv' in serial flash.

The launchpad is connected to a router & obtains an ip_adress. When any user who is in that network, enters this ip_address of the launchpad on their device browser, I want to give a link to DOWNLOAD the entire file i.e., 'myfile.csv'.

 href=myfile.csv target # =_blank>DOWNLOAD

adding above html line within <a> </a> in my code doesn't help me. ( i couldnt type the actual code here)

I also need to know if the solution would be different to download a file from a SD card that is interfaced to the launchpad.

Thanks in advance :)

**Comment by rei-vilo** [comment]
May I suggest to post your question at the 43oh forum at http://forum.43oh.com?

There a project for a SD library to leverage the flash of the LaunchPad.
