### ISSUE TITLE
Hex file not working in Proteus

### ISSUE THREAD

**Issue by Myonah** [energia/Energia#566]
The hex files for different example codes aren't working well in Proteus simulations.

**Comment by spirilis** [comment]
Can you elaborate?

**Comment by robertinant** [comment]
As Eric said, we would be happy to help but we need more information than just one line. For that reason I am closing this issue. Please feel free to reopen with more and complete info including how to reproduce. Also please consider to post the question on http://forum.43oh.com/forum/28-energia/ which will most likely get you a quicker answer if it is not an bug.

Thanks for reporting!
