### ISSUE TITLE
Energia MT: Wrong Link for Mac OS X

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#578]
The link to download Energia MT for Mac OS X on http://energia.nu/download/ points to previous release 14.

> Download here: energia-0101E0015-macosx.dmg 

points to 

`http://energia.nu/downloads/downloadv3.php?file=energia-0101E0014-macosx.dmg`

**Comment by robertinant** [comment]
Thanks for reporting! fixed..

**Comment by rei-vilo** [comment]
Still 

>
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>F9276DED4D07EB9E</RequestId>
<HostId>
CaT5QjqD6E4Xdka4RQZHwYVj1a+8oy9S0vshzzTkqQGNCL0hYqUUHmj/3W2cHL5T
</HostId>
</Error>
>

**Comment by robertinant** [comment]
Fixed. Issue on Amazon AWS not making the file public.

**Comment by rei-vilo** [comment]
Thanks!
