### ISSUE TITLE
No font hinting / antialiasing in Linux / Ubuntu

### ISSUE THREAD

**Issue by anton-veretenenko** [energia/Energia#579]
There is no font hinting / antialising in Linux / Ubuntu version. It does not respect system settings.
Two screenshots attached, using the same font face.
This is how it looks in Energia without hinting.
![hinting incorrect2](https://cloud.githubusercontent.com/assets/281043/6824999/bdefa2ec-d318-11e4-8175-6a149ab4140d.png)

This is how it should look when hinted (do not mind colors).
![hinting correct](https://cloud.githubusercontent.com/assets/281043/6824869/b866803a-d317-11e4-88e7-52e524474dc3.png)

**Comment by rei-vilo** [comment]
Have a look at the file `preferences.txt` and set editor.antialias` to `true`.

```
editor.antialias=true
```

On Mac OS X, the file is located under `~/Library/Energia/preferences.txt`.

**Comment by anton-veretenenko** [comment]
yep it works, close it then :)
