### ISSUE TITLE
usb_hid_feat

### ISSUE THREAD

**Issue by a-bhat1** [energia/Energia#580]
Add USB HID library and example to Energia.   The included example sends to and receives echoed data from the micro-controller.

**Comment by spirilis** [comment]
We've tried this before.  It's not simple.  I gave it a go about a month ago... Energia's build commands make it tricky to implement the MSP430 USB Developer's Package and Descriptor Tool outputs in a manner that's flexible enough for sketches to use.

**Comment by rei-vilo** [comment]
Which board?

**Comment by a-bhat1** [comment]
USBHID library has been tested on the MSP430F5529 board.  The USB stack has the ability to work with the F5xx and F6xx family of boards, however, I am not sure what needs to happen in Energia for HID library to work with boards other than MSP430F5529.

**Comment by robertinant** [comment]
This issue was moved to energia/msp430-lg-core#19
