### ISSUE TITLE
MSP432: No way to create sketches without TI-RTOS

### ISSUE THREAD

**Issue by WestfW** [energia/Energia#584]
The multi-tasking rtos support for MSP432 is exciting, but I still want to be able to create "bare metal" applications that don't use or load TI-RTOS, and that doesn't seem to be possible in 0101E0015; even the Blink example compiles to over 45k and links in the RTOS files.

**Comment by robertinant** [comment]
@WestfW, there is no plan for now to do a "bare metal" implementation for MSP432. We are looking into making single threaded Sketches "lighter" and hope to get close to the size of a "bare metal" implementation.
