### ISSUE TITLE
EZ430-CHRONOS support

### ISSUE THREAD

**Issue by murix** [energia/Energia#596]
Hi, 

What is the possibility of integrating support for the EZ430-CHRONOS?
Got a port for the AP (MSP430F5509 + CC1101) and watch (CC430F6137)

Link to EZ430-CHRONOS
http://www.ti.com/tool/ez430-chronos

**Comment by rei-vilo** [comment]
See Provide Guidelines to Add Support for New MCU #607

**Comment by rei-vilo** [comment]
See #912
