### ISSUE TITLE
eMT — Empty Folder or Dead Link — Home-Built Energia Fails to Compile

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#598]
The `emt @ 602e5f9` folder on the `master` branch is empty or the `emt @ 602e5f9` link is dead.

**Comment by rei-vilo** [comment]
I compiled **Energia** from the downloaded GitHub repository with the standard `ant dist`.

The resulting IDE fails to compile, as many core libraries —including `Arduino.h`— are missing.
![capture 2015-04-07 a 00 35 35](https://cloud.githubusercontent.com/assets/951776/7022669/77ddc016-dd2e-11e4-9a42-1832514e83d2.png)

Comparing the home built Energia with the official distribution shows many files are just gone. Are they supposed to be in the `emt` missing folder or dead link?
![capture 2015-04-07 a 00 31 47](https://cloud.githubusercontent.com/assets/951776/7022672/89a844ce-dd2e-11e4-85b7-11744d6f7443.png)

**Comment by rei-vilo** [comment]
From http://forum.43oh.com/topic/8347-energia-15-built-from-source-wont-compile-msp432/?p=65059
>
The Energia repository has a temporary submodule called emt that points to a private repository on a different server. This repository will eventually be merged into the Energia main repository. The files that are "missing" are symbolic links to that repository. Hence if the content of the submodule is missing then the files are missing in the Energia repo. To work around this for now, you could copy the files from the release to the Energia repository. The files to copy are hardware/common/* and hardware/msp432/*
>
I hope to have these files in the main Energia repository later this month.
> 
Hope that helps.
Robert
>

**Comment by rei-vilo** [comment]
Still dead link or missing folder after commit 	69b57433b73820b0aadd2bb9dd4415f7c2cf18ee.
![capture 2015-04-17 a 21 00 56](https://cloud.githubusercontent.com/assets/951776/7209039/1cb6ac24-e545-11e4-8b6a-8d7e763b5300.png)

**Comment by robertinant** [comment]
The emt submodule is no longer used in Energia 18. The core is not located in it's separate package and repository.
