### ISSUE TITLE
CC3200 : "Failed to trigger boot loader" Error When Uploading

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#624]
When uploading to the CC3200 LaunchPad,

```
/Applications/Energia.app/Contents/Resources/Java/hardware/tools/lm4f/bin/cc3200prog /dev/cu.usbserial-cc3200B Builds/embeddedcomputing.bin
```

it fails in 90% of the cases with the following error message:

>
Open UART /dev/cu.usbserial-cc3200B
open UART success
Read ACK failed
Failed to trigger boot loader
>

How to improve the reliability and capability of the upload process?

**Comment by flety-emmanuel** [comment]
good point. I think it's due to what robertinant mentioned, a ACK timeout on the UART that is a bit short. The reset of the launchpad seems to be a bit different than with the CC3200 mod. We forced the reset to be a bit faster to match the ACK most of the time but we still have issues about this. I believe that it totally depend on how fast the chip resets, an average has to be found I suppose. I longer timeout is better to match more different cases / board designs.

**Comment by robertinant** [comment]
What is the size of the binary?

**Comment by rei-vilo** [comment]
The *blinky*
> Estimated Flash:  2976 bytes used

A web-server
> Estimated Flash:  47952 bytes used

**Comment by flety-emmanuel** [comment]
similar on my end, tried various example codes of similar size, and up to 101 kb for my "full" program.
Sometimes a fix to this is to keep the CC3200 in reset until energia says uploading, then manually release from reset. Most of the time the auto reset works.
Also, sometimes the upload time is a blitz (even for 100 kb), sometimes it will take ages for the very same binary

**Comment by robertinant** [comment]
I have increased the uart receive timeout and this seems to have fixed the issue in most cases. This fix is available in Energia 16. If you are still seeing the issue then please reopen.

**Comment by flety-emmanuel** [comment]
Thanks a lot Robert, that will help for sure !
I'll give a try to energia v16 !

cheers,
Manu

**Comment by scopedial** [comment]
I have downloaded energia 16 and I am having the same problem as above. I was uploading just "Blinky".

**Comment by flety-emmanuel** [comment]
works for us both on mac and windows

**Comment by rickenbroc** [comment]
I also still have the problem too with max osx 10.6.8 both with energia stand alone and CCS cloud

**Comment by nickstoughton** [comment]
I still see this issue with Energia 0101E0016 and Mac OS/X El Capitan (10.11). I can upload successfully about 1 time in 100. For the rest, the commonest problem (~90%) is "Failed to trigger bootloader". I also see UART Receive Timeout (~8%) and Timeout during upload (~2%) (?not sure about the spelling of this one). The binary is small (Downloading file "/sys/mcuimg.bin" with size 25776).

**Comment by Jason0416** [comment]
CC3200MOD LaunchPad,Stillllllll "Failed to trigger boot loader"

**Comment by rei-vilo** [comment]
@Jason0416 Please, which operating system, Energia releases do you use?

**Comment by robertinant** [comment]
Have you followed the guide posted here? http://energia.nu/cc3200guide/
Also make sure that you have the drivers installed as per guide here:http://energia.nu/guide/
It would help if you could post the output in the little black window in Energia here.

**Comment by val123456** [comment]
Note my daughter is seeing this same error while trying to get it running for a class . . . OS X 10.11.

**Comment by fletcherbach-temboo** [comment]
Having the same problem here: 
MacOS 10.12.3 - Retina Macbook Pro - 2015
Energia 1.6.10E18
TI LaunchPadXL CC3200

I followed the launchpad setup guide for MacOS, but might be worth noting that is my first time working with the board and the IDE. 

Console output:
`
Sketch uses 29,848 bytes (11%) of program storage space. Maximum is 262,144 bytes.
Open UART /dev/cu.usbserial-cc3200B
open UART success
Read ACK failed
Failed to trigger bootloader
An error occurred while uploading the sketch
`

**Comment by rei-vilo** [comment]
@fletcherbach-temboo 

- Is the LaunchPad configured for upload? 

![2978393_orig](https://cloud.githubusercontent.com/assets/951776/23070355/2ecb6bd2-f52b-11e6-97f3-10c40fce97f9.png)
 
Most of the times, this message is a false-positive. 

- Does the sketch run on the board?

In that case, you can ignore the message.

**Comment by fletcherbach-temboo** [comment]
@rei-vilo Success! 

I jumped TCK to SOP2 per your suggestion and it solved the problem. Thanks for posting the solution and thanks for the quick attention.

**Comment by rei-vilo** [comment]
You're welcome!

Full explanation is available at http://energia.nu/cc3200guide/ (mentioned at https://github.com/energia/Energia/issues/624#issuecomment-180018100).
