### ISSUE TITLE
MSP432: 80 MHz for clockCyclesPerMicrosecond

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#633]
File **/Applications/ IDE/ Energia.app/ Contents/ Resources/ Java/ hardware/ msp432/ cores/ msp432/ Energia.h** contains 

```
#define clockCyclesPerMicrosecond() ( 80000000L / 1000000L )
```

Shouldn't be `48000000`= 48 MHz instead?

**Comment by robertinant** [comment]
This issue was moved to energia/msp432-core#31
