### ISSUE TITLE
Energia 0101E0015-macosx.dmg damaged/will not run

### ISSUE THREAD

**Issue by jnshadow** [energia/Energia#639]
Using MAC OS X 10.10.3 on Macbook.  Currently running Energia 14 successfully.  DMG for 15 opens, can read contents but will not run.

![energiadmg](https://cloud.githubusercontent.com/assets/5483021/8286479/d238439e-18d7-11e5-86a5-083762db07b7.jpg)

**Comment by rei-vilo** [comment]
This is the protection mechanism from Mac OS X. 

Please refer to the [Setup Energia on Mac OS X](http://energia.nu/guide/guide_macosx/) guide.
