### ISSUE TITLE
Energia MT: Questions about Task Management by Energia 

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#641]
By default, Energia considers each sketch as a task with two functions: initial `setup()` and to-be-repeated `loop()`. 

Energia performs some under-the-hood work: it runs the function `setup()` once and includes the `loop()` function inside an endless loop.  

As a consequence for a task created with the Task library, the function of the task needs to be called explicitly by a timer or a clock. 

So the questions are: 
* Does the under-the-hood work performed by Energia hide too much RTOS?
* Does the under-the-hood work performed by Energia provide too limited a version of RTOS?

For more detail and a discussion on the three solutions I've explored, please refer to [this page on my website](http://embeddedcomputing.weebly.com/task-library.html).

**Comment by robertinant** [comment]
If additional tasks need to be created then a new tab with a setup and loop should be used. Currently it is not possible to set the priority of the task. This is something we will be looking into so that the user can set the priority of the task (setup()/loop() tuple)
