### ISSUE TITLE
One-Wire Library

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#65]
Add one-wire library

**Comment by Lwangaman** [comment]
Sorry if I continue the topic even though it's been closed... I have successfully used the OneWire library found here http://www.pjrc.com/teensy/td_libs_OneWire.html in the Arduino IDE. I would now like to use it in Energia so that I can't port my code fairly easily. I am trying to include the library among the Energia libraries, but the I/O definitions / register types need to be updated for the boards that Energia supports. Specifically lines 51-109 in OneWire.h:

    // Platform specific I/O definitions
    
    #if defined(__AVR__)
    #define PIN_TO_BASEREG(pin)             (portInputRegister(digitalPinToPort(pin)))
    #define PIN_TO_BITMASK(pin)             (digitalPinToBitMask(pin))
    #define IO_REG_TYPE uint8_t
    #define IO_REG_ASM asm("r30")
    #define DIRECT_READ(base, mask)         (((*(base)) & (mask)) ? 1 : 0)
    #define DIRECT_MODE_INPUT(base, mask)   ((*((base)+1)) &= ~(mask))
    #define DIRECT_MODE_OUTPUT(base, mask)  ((*((base)+1)) |= (mask))
    #define DIRECT_WRITE_LOW(base, mask)    ((*((base)+2)) &= ~(mask))
    #define DIRECT_WRITE_HIGH(base, mask)   ((*((base)+2)) |= (mask))
    
    #elif defined(__MK20DX128__)
    #define PIN_TO_BASEREG(pin)             (portOutputRegister(pin))
    #define PIN_TO_BITMASK(pin)             (1)
    #define IO_REG_TYPE uint8_t
    #define IO_REG_ASM
    #define DIRECT_READ(base, mask)         (*((base)+512))
    #define DIRECT_MODE_INPUT(base, mask)   (*((base)+640) = 0)
    #define DIRECT_MODE_OUTPUT(base, mask)  (*((base)+640) = 1)
    #define DIRECT_WRITE_LOW(base, mask)    (*((base)+256) = 1)
    #define DIRECT_WRITE_HIGH(base, mask)   (*((base)+128) = 1)
    
    #elif defined(__SAM3X8E__)
    // Arduino 1.5.1 may have a bug in delayMicroseconds() on Arduino Due.
    // http://arduino.cc/forum/index.php/topic,141030.msg1076268.html#msg1076268
    // If you have trouble with OneWire on Arduino Due, please check the
    // status of delayMicroseconds() before reporting a bug in OneWire!
    #define PIN_TO_BASEREG(pin)             (&(digitalPinToPort(pin)->PIO_PER))
    #define PIN_TO_BITMASK(pin)             (digitalPinToBitMask(pin))
    #define IO_REG_TYPE uint32_t
    #define IO_REG_ASM
    #define DIRECT_READ(base, mask)         (((*((base)+15)) & (mask)) ? 1 : 0)
    #define DIRECT_MODE_INPUT(base, mask)   ((*((base)+5)) = (mask))
    #define DIRECT_MODE_OUTPUT(base, mask)  ((*((base)+4)) = (mask))
    #define DIRECT_WRITE_LOW(base, mask)    ((*((base)+13)) = (mask))
    #define DIRECT_WRITE_HIGH(base, mask)   ((*((base)+12)) = (mask))
    #ifndef PROGMEM
    #define PROGMEM
    #endif
    #ifndef pgm_read_byte
    #define pgm_read_byte(addr) (*(const uint8_t *)(addr))
    #endif
    
    #elif defined(__PIC32MX__)
    #define PIN_TO_BASEREG(pin)             (portModeRegister(digitalPinToPort(pin)))
    #define PIN_TO_BITMASK(pin)             (digitalPinToBitMask(pin))
    #define IO_REG_TYPE uint32_t
    #define IO_REG_ASM
    #define DIRECT_READ(base, mask)         (((*(base+4)) & (mask)) ? 1 : 0)  //PORTX + 0x10
    #define DIRECT_MODE_INPUT(base, mask)   ((*(base+2)) = (mask))            //TRISXSET + 0x08
    #define DIRECT_MODE_OUTPUT(base, mask)  ((*(base+1)) = (mask))            //TRISXCLR + 0x04
    #define DIRECT_WRITE_LOW(base, mask)    ((*(base+8+1)) = (mask))          //LATXCLR  + 0x24
    #define DIRECT_WRITE_HIGH(base, mask)   ((*(base+8+2)) = (mask))          //LATXSET + 0x28
    
    #else
    #error "Please define I/O register types here"
    #endif

I have no idea how to go about doing this... If there is a reference somewhere I suppose I could try to tackle it, and it could be included here in the repository among the available libraries... If anyone can point me to an example definition of the register types for the boards supported by Energia.

**Comment by spirilis** [comment]
Best to look for a OneWire lib already ported.

**Comment by Lwangaman** [comment]
do you know of one?
I have found some suggestions on some forums and I can now get the code to compile but I'll have to test it with my MSP430 tomorrow to see if it'll work ok...

    #elif defined(__TM4C129XNCZAD__) || defined(__TM4C1294NCPDT__) || defined(__LM4F120H5QR__) || defined(__TM4C123GH6PM__)
    #define portMaskedOutputRegister(base, mask) \
  ((volatile uint8_t *) (base + (GPIO_O_DATA + (((uint32_t)mask) << 2))))
    #define PIN_TO_BASEREG(pin)             (&((uint32_t)portBASERegister(digitalPinToPort(pin))))
    #define PIN_TO_BITMASK(pin)             (digitalPinToBitMask(pin))
    #define IO_REG_TYPE uint8_t
    #define IO_REG_ASM
    #define DIRECT_READ(base, mask)
    #define DIRECT_MODE_INPUT(base, mask)
    #define DIRECT_MODE_OUTPUT(base, mask)
    #define DIRECT_WRITE_LOW(base, mask)  (portMaskedOutputRegister(base, mask) = 0)
    #define DIRECT_WRITE_HIGH(base, mask) (portMaskedOutputRegister(base, mask) = 0xFF)
    
    #else
    //#error "Please define I/O register types here"
    #define PIN_TO_BASEREG(pin)            (0) // dummy not used in fallback mode
    #define PIN_TO_BITMASK(pin)            ( pin ) // use for pin # fallback mode
    #define IO_REG_TYPE uint32_t
    #define IO_REG_ASM                    // not used
    #define DIRECT_READ(base, pin)       digitalRead(pin)
    #define DIRECT_WRITE_LOW(base, pin)  digitalWrite(pin, LOW)
    #define DIRECT_WRITE_HIGH(base, pin) digitalWrite(pin, HIGH)
    #define DIRECT_MODE_INPUT(base, pin) pinMode(pin,INPUT)
    #define DIRECT_MODE_OUTPUT(base, pin) pinMode(pin,OUTPUT)
    #endif

**Comment by watkinrt** [comment]
Like Lwangaman, I was unable to find the officially ported version of OneWire for MSP430 in Energia. The above modification to the original OneWire Arduino code seems to work; however, the digital I/O can be optimized a little bit to speed things up:

```
// Platform specific I/O definitions

#if defined(__AVR__)
#define PIN_TO_BASEREG(pin)             (portInputRegister(digitalPinToPort(pin)))
#define PIN_TO_BITMASK(pin)             (digitalPinToBitMask(pin))
#define IO_REG_TYPE uint8_t
#define IO_REG_ASM asm("r30")
#define DIRECT_READ(base, mask)         (((*(base)) & (mask)) ? 1 : 0)
#define DIRECT_MODE_INPUT(base, mask)   ((*((base)+1)) &= ~(mask))
#define DIRECT_MODE_OUTPUT(base, mask)  ((*((base)+1)) |= (mask))
#define DIRECT_WRITE_LOW(base, mask)    ((*((base)+2)) &= ~(mask))
#define DIRECT_WRITE_HIGH(base, mask)   ((*((base)+2)) |= (mask))

...

#elif defined(__MSP430__)
#define PIN_TO_BASEREG(pin)             (portInputRegister(digitalPinToPort(pin)))
#define PIN_TO_BITMASK(pin)             (digitalPinToBitMask(pin))
#define IO_REG_TYPE uint8_t
#define IO_REG_ASM 
#define DIRECT_READ(base, mask)         (((*(base)) & (mask)) ? 1 : 0)  // PXIN
#define DIRECT_MODE_INPUT(base, mask)   ((*((base)+4)) &= ~(mask))      // PXDIR
#define DIRECT_MODE_OUTPUT(base, mask)  ((*((base)+4)) |= (mask))       // PXDIR
#define DIRECT_WRITE_LOW(base, mask)    ((*((base)+2)) &= ~(mask))      // PXOUT
#define DIRECT_WRITE_HIGH(base, mask)   ((*((base)+2)) |= (mask))       // PXOUT

#else
#error "Please define I/O register types here"
#endif
```

Note that this is very similar to the Arduino (__AVR__) definition, except for the DIRECT_MODE_INPUT and DIRECT_MODE_OUTPUT definitions as the base address registries (such as P1DIR, P1OUT, P1IN, etc) are ordered differently than for Arduinos.
