### ISSUE TITLE
CC3200_LAUNCHXL/Board.h:1:1: error: expected unqualified-id before '.' token

### ISSUE THREAD

**Issue by kingofl337** [energia/Energia#650]
Can't compile CC3200 emt projects with Energia  E1010E0016. Normal CC3200 projects work. (windows 8 32bit)
Energia was built with ant 1.9.5, jdk-8u45 Cygwin 2.871, 32bit versions.

I've tried to compile multiblink and normal blink and it get this error on compile.

C:\energia_62815/hardware/cc3200emt/variants/CC3200_LAUNCHXL/Board.h:1:1: error: expected unqualified-id before '.' token
 ../../../../emt/src/ti/runtime/wiring/cc3200/variants/CC3200_LAUNCHXL/Board.h
 ^
main.cpp:36:3: error: 'setupsketch_jun28a' was not declared in this scope
  {setupsketch_jun28a, loopsketch_jun28a}
   ^
main.cpp: In function 'int main()':
main.cpp:88:13: error: 'Board_init' was not declared in this scope
  Board_init();  /* this function is generated as part of TI-RTOS config */
             ^
make: *** [main.obj] Error 1
C:\energia_62815\tools\common\bin\make returned 2

**Comment by rei-vilo** [comment]
Same as #645
