### ISSUE TITLE
CC3200: BLUE_LED as YELLOW_LED instead of GREEN_LED

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#653]
For improved consistency across the boards, replace in `Energia.app/ Contents/ Resources/ Java/ hardware/ cc3200emt/ variants/ CC3200_LAUNCHXL/ pins_energia.h`

```
static const uint8_t BLUE_LED = 10; /* mapped to same as GREEN_LED */
```

by 

```
static const uint8_t BLUE_LED = 9; /* mapped to same as YELLOW_LED */
```

Same for plain CC3200 LaunchPad.

**Comment by robertinant** [comment]
In the meantime BLUE_LED was removed and replaced with YELLOW_LED.
