### ISSUE TITLE
OneMSTimer Library requires different order of include files to compile for CC3200EMT

### ISSUE THREAD

**Issue by StefanSch** [energia/Energia#656]
OneMSTimer Library requires different order of include files to compile for CC3200EMT (see below)
also the define to identify it as CC3200 in the EMT mode needs to be added

#if defined(__CC3200R1M1RGC__) || defined(TARGET_IS_CC3200) 

#include <inc/hw_types.h>
#include <inc/hw_memmap.h>
#include <inc/hw_gprcm.h>
#include "inc/hw_timer.h"
#include <driverlib/prcm.h>
#include <driverlib/rom_map.h>
#include <driverlib/pin.h>
#include <driverlib/timer.h>

**Comment by robertinant** [comment]
This has been fixed when I moved EMT targets to use Clock module.
