### ISSUE TITLE
FR4133 and FR6989: Provide Library for 6-Digit 16-Segment LCD

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#660]
Provide library for 6-digit 16-segment LCD for MSP430FR4133 and MSP430FR6989 LaunchPads.

**Comment by rei-vilo** [comment]
See branch issue_600 at https://github.com/energia/Energia/tree/issue_660/hardware/msp430/libraries/LCD_Launchpad

Thank you, @StefanSch

**Comment by StefanSch** [comment]
already merged to master
