### ISSUE TITLE
issue energia and knob mode

### ISSUE THREAD

**Issue by Nikromante** [energia/Energia#661]
Hi, people, I'm new on this energia stuff, and I have some trouble withe the knob mode Example for servo, I just open the default example on energia for test my servo with my MSP430, but after the failed compiling I got some errors, like overflow in the code, this is the example code:
---------------------------------
// Controlling a servo position using a potentiometer (variable resistor) 
// by Michal Rinott <http://people.interaction-ivrea.it/m.rinott> 

#include <Servo.h> 
 
Servo myservo;  // create servo object to control a servo 
 
int potpin = 0;  // analog pin used to connect the potentiometer
int val;    // variable to read the value from the analog pin 
 
void setup() 
{ 
  myservo.attach(9);  // attaches the servo on pin 9 to the servo object 
} 
 
void loop() 
{ 
  val = analogRead(potpin);            // reads the value of the potentiometer (value between 0 and 1023) 
  val = map(val, 0, 1023, 0, 179);     // scale it to use it with the servo (value between 0 and 180) 
  myservo.write(val);                  // sets the servo position according to the scaled value 
  delay(15);                           // waits for the servo to get there 
} 

---------------------------------
After this I want to compile but all the time I just got:
---------------------------------
c:/energia-0101e0015/hardware/tools/msp430/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/bin/ld.exe: Knob.cpp.elf section `.rodata' will not fit in region `rom'
c:/energia-0101e0015/hardware/tools/msp430/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/bin/ld.exe: section .vectors loaded at [0000ffe0,0000ffff] overlaps section .rodata loaded at [0000ff4e,0000ffe3]
c:/energia-0101e0015/hardware/tools/msp430/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/bin/ld.exe: region `rom' overflowed by 4 bytes
collect2: ld returned 1 exit status

---------------------------------
It's like a overflow, how can I fix this, by the way is the only example with this problem, or some one can bring me a new Knob servo example?

thanks for the attention.

**Comment by rei-vilo** [comment]
The [43oh forum](http://forum.43oh.com) may be a more appropriate place to post your question.
