### ISSUE TITLE
C2000 Uploads fail on F28027F LaunchPad

### ISSUE THREAD

**Issue by treygerman** [energia/Energia#662]
Because of the different ROM variants between the F28027 and F28027F devices, serial flash programming fails when it is attempted with the "InstaSPIN" F28027F LaunchPad.  

This should be fixable by adding a 3rd C2000 board variant for the F28027F and building a serial flash kernel using the propper ROM symbol library.

**Comment by rei-vilo** [comment]
New uploader utility. See #754.
