### ISSUE TITLE
OPT3001 header file case mismatch in MSP430 libraries

### ISSUE THREAD

**Issue by aftisyst** [energia/Energia#664]
Getting Energia sketch build failures on Linux with error:

root/energia-0101E0016/hardware/msp430/libraries/OPT3001/OPT3001.cpp:7:21: fatal error: opt3001.h: No such file or directory

This is due to the OPT.cpp referencing header file "opt3001.h", while the filesystem has file "OPT3001.h".  The case mismatch causes the file to not be found on Linux, hence Linux sketch build failures.

**Comment by robertinant** [comment]
Thanks for the report! Fixed!
