### ISSUE TITLE
AccelerometerLED sketch does not build for msp430g2231

### ISSUE THREAD

**Issue by aftisyst** [energia/Energia#669]
The msp430g2231 AccelerometerLED sketch under EducationalBP_MKII does not successfully link for the msp430g2231:

Building target: AccelerometerLED.out
Invoking: GNU Linker
"@root/energia-0101E0016/hardware/tools/msp430/bin/msp430-gcc" -mmcu=msp430g2231 -DF_CPU=1000000L -DENERGIA=16 -DARDUINO=101 -Os -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -Wall -Wl,--gc-sections -L"@workspace/lpmsp430g2231_core/Debug" -Wl,--undefined,main -fmax-errors=10 -o"AccelerometerLED.out" "./AccelerometerLED.o" -Wl,--start-group -l"lpmsp430g2231_core" -l"m" -Wl,--end-group 
@root/energia-0101E0016/hardware/tools/msp430/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/bin/ld: AccelerometerLED.out section `.text' will not fit in region `rom'
@root/energia-0101E0016/hardware/tools/msp430/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/bin/ld: section .vectors loaded at [0000ffe0,0000ffff] overlaps section .text loaded at [0000f800,000101cb]
@root/energia-0101E0016/hardware/tools/msp430/bin/../lib/gcc/msp430/4.6.3/../../../../msp430/bin/ld: region `rom' overflowed by 720 bytes
@root/energia-0101E0016/hardware/tools/msp430/bin/../lib/gcc/msp430/4.6.3/libcrt0.a(_copy_data.o): In function `__do_copy_data':
/home2/kimballr/mspgcc_energia/BUILD/gcc/gcc/../../../gcc/gcc/config/msp430/crt0.S:195: relocation truncated to fit: R_MSP430_16_BYTE against symbol `__data_load_start' defined in *ABS* section in AccelerometerLED.out
@workspace/lpmsp430g2231_core/Debug/liblpmsp430g2231_core.a(main.o): In function `main':
@root/energia-0101E0016/hardware/msp430/cores/msp430/main.cpp:5: relocation truncated to fit: R_MSP430_16 against symbol `init' defined in .text.init section in @workspace/lpmsp430g2231_core/Debug/liblpmsp430g2231_core.a(wiring.o)
@workspace/lpmsp430g2231_core/Debug/liblpmsp430g2231_core.a(TimerSerial.o): In function `TimerSerial':
@root/energia-0101E0016/hardware/msp430/cores/msp430/TimerSerial.cpp:90: relocation truncated to fit: R_MSP430_16_BYTE against symbol `vtable for TimerSerial' defined in .rodata._ZTV11TimerSerial section in @workspace/lpmsp430g2231_core/Debug/liblpmsp430g2231_core.a(TimerSerial.o)
@workspace/lpmsp430g2231_core/Debug/liblpmsp430g2231_core.a(TimerSerial.o): In function `TimerSerial::begin(unsigned long)':
@root/energia-0101E0016/hardware/msp430/cores/msp430/TimerSerial.cpp:111: relocation truncated to fit: R_MSP430_16 against symbol `__udivsi3' defined in .text.libgcc section in @root/energia-0101E0016/hardware/tools/msp430/bin/../lib/gcc/msp430/4.6.3/libgcc.a(_udivmod32.o)
@root/energia-0101E0016/hardware/tools/msp430/bin/../lib/gcc/msp430/4.6.3/crt0ivtbl16.o: In function `__isr_14':
(.text+0x2): relocation truncated to fit: R_MSP430_16 against symbol `_unexpected_' defined in .text.crt0 section in @root/energia-0101E0016/hardware/tools/msp430/bin/../lib/gcc/msp430/4.6.3/libcrt0.a(_unexpected_.o)
@root/energia-0101E0016/hardware/tools/msp430/bin/../lib/gcc/msp430/4.6.3/crt0ivtbl16.o:(.vectors+0x14): relocation truncated to fit: R_MSP430_16_BYTE against symbol `__isr_10' defined in .text.watchdog_isr section in @workspace/lpmsp430g2231_core/Debug/liblpmsp430g2231_core.a(wiring.o)
./AccelerometerLED.o: In function `loop':
@workspace/AccelerometerLED/AccelerometerLED.ino:53: relocation truncated to fit: R_MSP430_16_BYTE against `no symbol'
@workspace/AccelerometerLED/AccelerometerLED.ino:55: relocation truncated to fit: R_MSP430_16_BYTE against `no symbol'
@workspace/AccelerometerLED/AccelerometerLED.ino:69: relocation truncated to fit: R_MSP430_16_BYTE against `no symbol'
@workspace/AccelerometerLED/AccelerometerLED.ino:71: relocation truncated to fit: R_MSP430_16_BYTE against `no symbol'
@workspace/AccelerometerLED/AccelerometerLED.ino:85: additional relocation overflows omitted from the output
collect2: ld returned 1 exit status
gmake: *** [AccelerometerLED.out] Error 1
gmake: Target `all' not remade because of errors.

**** Build Finished ****

**Comment by rei-vilo** [comment]
Same answer as for #668.
