### ISSUE TITLE
MSP432 EMT and CC3200 EMT: Incompatible DHT Grove Library

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#675]
The Grove DHT library uses `noInterrupts();` and `interrupts();` for the temperature and humidity sensor.

Compilation fails with the following error messages:

>
'noInterrupts' was not declared in this scope
'interrupts' was not declared in this scope
>

**Comment by rei-vilo** [comment]
Possible solution at #679.

**Comment by robertinant** [comment]
This issue was moved to energia/msp432-core#30
