### ISSUE TITLE
some secondary functions are not setup correct in the FR4133 and FR6989

### ISSUE THREAD

**Issue by StefanSch** [energia/Energia#676]
secondary function for 
FR4133
 pin 10, 24,23
FR 6989
 pin 43, 44, 

are not setup correct

**Comment by robertinant** [comment]
@StefanSch, is this issue already addressed?

**Comment by StefanSch** [comment]
The coding is done - I am just now in the testing phase

**Comment by StefanSch** [comment]
just pushed the fix - please merge from branch issue_676

**Comment by StefanSch** [comment]
already in master
