### ISSUE TITLE
Turning off ADC in wiring_analog.c

### ISSUE THREAD

**Issue by nicholasjconn** [energia/Energia#680]
According to the MSP430FR5969 user guide, the ADC12ON bit can only be modified when ADC12ENC is cleared. The ADC12ENC bit does not appear to be cleared at all.

Code:

    /* POWER: Turn ADC and reference voltage off to conserve power */
    ADC12CTL0 &= ~(ADC12ON);
    REFCTL0 &= ~(REFON);

**Comment by StefanSch** [comment]
each new conversion starts with a 
    ADC12CTL0 &= ~ADC12ENC;                 // disable ADC
So before any changes are applied it is ensured that the ENC bit is cleared.
