### ISSUE TITLE
CC3200 WiFi: How to Get the MAC Address

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#687]
Here's a simple function to get the MAC address of the CC3200. 

Would be great to integrate it to the WiFi library along with the `getRemoteIP()` as per #621.

```
    uint8_t macAddressVal[SL_MAC_ADDR_LEN];
    uint8_t macAddressLen = SL_MAC_ADDR_LEN;
    sl_NetCfgGet(SL_MAC_ADDRESS_GET,NULL,&macAddressLen,macAddressVal);
    MACAddress MAC(macAddressVal);
    Serial.print("MAC = ");
    Serial.println(MAC);
```

**Comment by robertinant** [comment]
This would be an non standard WiFi library API. What is the need for getting the MAC address of the CC3200?

**Comment by rei-vilo** [comment]
To ease configuration, as some routers require the list of the MAC addresses to allow access.

**Comment by rei-vilo** [comment]
Added ** GetMacAddress ** example at https://github.com/energia/Energia/tree/master/hardware/cc3200/libraries/WiFi/examples/GetMacAddress
