### ISSUE TITLE
MSP430: time.h not included?

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#694]
The `time.h` library provides all the routines to manage date and time. It is a standard C library provided with GCC.

I'm using it successfully with LM4F / TM4C, MSP432, CC3200. However, `#include "time.h"` and  `#include <time.h>` fail when compiling against MSP430G2553, MSP430F5529 and alike. 

The folder `Energia.app/Contents/Resources/Java/hardware/tools/msp430 doesn't contain it, contrary to all other platforms.

Any plans to include the `time.h` library for the MSP430 platform?

**Comment by robertinant** [comment]
This will be fixed ones I move MSP430 to the new RedHat MSP430 GCC in Energia 17.
