### ISSUE TITLE
MSP432 SDSPI - SPI

### ISSUE THREAD

**Issue by cevatbostancioglu** [energia/Energia#699]
Hello , 
i found in board_init.c file , sdspi code. 
they said it's for sd cards.
is this working on energia ?

i found a lot of msp432 sd card libraries but no one working.

**Comment by robertinant** [comment]
SD card is not supported in the current versions of Energia and there is no plan to support it in the near future.

**Comment by rei-vilo** [comment]
As a temporary solution, have a look at the [SD_TM4C](https://github.com/rei-vilo/SD_TM4C) library. It works fine on the LM4F and TM4C MCUs.
