### ISSUE TITLE
Truncated output in console when compiling

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#703]
The console seems to be limited in size. 

Whatever the verbose option turned on or off, first lines are removed.

For example, compiling against the CC3200 EMT floods the console with warnings.

Is there a way to obtain the full output without being truncated?

**Comment by robertinant** [comment]
I am not able to reproduce this in Energia 16. All lines are shown in the console. Can you post an example output here?

**Comment by rei-vilo** [comment]
When the output for compilation and upload is larger than a given size, first lines are missing.

**Comment by rei-vilo** [comment]
This also occurs with the Arduino IDE. When **Show verbose output during** **compilation** and **upload** are both selected, the trace for upload may erase the trace from compilation.

So I'm flagging this ticket as **Not Energia Specific** and closing it.
