### ISSUE TITLE
MSP430F5529 LaunchPad RAM Size: 1KB or 8KB?

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#705]
Energia shows 1KB for RAM size. 

Shouldn't be 8KB RAM as per the [features list](http://www.ti.com/tool/MSP-EXP430F5529LP), unless there's a technical restriction?

From `boards.txt`
```
lpmsp430f5529.upload.maximum_ram_size=1024
lpmsp430f5529_25.upload.maximum_ram_size=1024
```

**Comment by robertinant** [comment]
I have corrected the RAM size for all boards.
