### ISSUE TITLE
MSP430FR6869: Implement I²C on Pins 9 + 10 for Compatibility with BoosterPacks

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#708]
I²C is already implemented on pins 14 and 15, with SPI port.

BoosterPack standard requires I²C on pins 9 + 10, as per [Design Reference](http://www.ti.com/ww/en/launchpad/dl/boosterpack-pinout-v2.pdf) updated Dec 30, 2013.

Thank you!

**Comment by rei-vilo** [comment]
Use `setModule()` function as for the Tiva C implementation.

**Comment by StefanSch** [comment]
I am just working on this - so you can assign this to me.

**Comment by rei-vilo** [comment]
@StefanSch Thank you and good luck!

**Comment by StefanSch** [comment]
implemented on Branch issue_708 and merged to master
