### ISSUE TITLE
sslConnect() Compatibility Issue in Client.h

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#714]
Shouldn't we include the solution for [Libraries working in Energia 13 and also in arduino but not in Energia 14](http://forum.43oh.com/topic/6242-libraries-working-in-energia-13-and-also-in-arduino-but-not-in-energia14/?p=53933) posted 02 January 2015 - 11:34 PM?

>
Thanks for sending the libraries in an e-mail.
>
There is a backwards compatibility issue with sslConnect() that was added in Energia 14. The sslConnect() functions are declared as pure virtual. Since the ActionClient derived from Client does not implement sslConnect() compilation will fail. The solution is to offer a default empty implementation of sslConnect() in Client.h.
>
Please edit hardware/cc3200/cores/cc3200/Client.h and replace:
```
virtual int sslConnect(const char *host, uint16_t port);
virtual int sslConnect(IPAddress ip, uint16_t port);
```
with:
```
virtual int sslConnect(const char *host, uint16_t port){};
virtual int sslConnect(IPAddress ip, uint16_t port){};
```
Robert
>

**Comment by robertinant** [comment]
Fixed with 07147476a29062e17bffc7a1eaaae5a785d5669a
