### ISSUE TITLE
cc3200 compile driverlib from source  option creates compiler errors

### ISSUE THREAD

**Issue by seanguzz** [energia/Energia#723]
energia-0101E0016\hardware\cc3200\cores\cc3200\driverlib\dma_hal.c:38:22: fatal error: cc_types.h: No such file or directory
 #include "cc_types.h"
                      ^
compilation terminated.

**Comment by seanguzz** [comment]
I assume that the option is using the makefile found inside the cc3200\cores\cc3200\driberlib
is this correct?

**Comment by robertinant** [comment]
Fixed.
