### ISSUE TITLE
Port U8Glib to Energia

### ISSUE THREAD

**Issue by overkillthemighty** [energia/Energia#726]
U8Glib supports a ton of displays and appears to be fairly hardware agnostic. I tried importing it in the library folder, but it seems like the include in the initial .h file is not being picked up or something (lots of undefined references that are defined in the clib/u8g.h file)
I moved the files in that subfolder (clib) up, but it is still throwing:

ug8lib\u8g_dev_st7920_128x64.c.o:(.data.u8g_dev_st7920_128x64_4x_sw_spi+0x8): undefined reference to `u8g_com_arduino_st7920_spi_fn'
collect2.exe: error: ld returned 1 exit status

It looks like that is defined in u8g.h line 669.
I may be tired here, but I am not sure what I am missing.

**Comment by rei-vilo** [comment]
There are already many libraries available for Energia: 

* RobG's [(Universal) Colour LCD graphics library](http://forum.43oh.com/topic/4352-universal-color-lcd-graphics-library-2) and 
* my [LCD_screen Library Suite](http://embeddedcomputing.weebly.com/lcd_screen-library-suite.html).

The [43oh forum](http://forum.43oh.com) seems a more appropriate place to post your request.
