### ISSUE TITLE
Hibernate Tiva C 123GXL

### ISSUE THREAD

**Issue by luylucas10** [energia/Energia#737]
Hi everyone.
I'm working with Tiva C launchpad and I want to know How can I set hibernate or other low power mode on this launchpad with Energia IDE? I have searched a lot, but I don't found a solution for me.

Write, if possible, a code example please.

Thanks for reply!

**Comment by rei-vilo** [comment]
See http://energia.nu/reference/sleep/

**Comment by luylucas10** [comment]
Thank you! Thank you very much. It's helping me so much!
I could reduce energy consumption by almost half with suspend() and wakeup().
