### ISSUE TITLE
Sleep() not defined in EMT

### ISSUE THREAD

**Issue by measley** [energia/Energia#742]
Sleep() does not appear to be defined in EMT (MSP432, CC3200)

I replaced sleep() with delay in blink.ino and got following error. 

Blink.ino:32:13: error: 'sleep' was not declared in this scope

I understand the delay already has low power modes enabled, do we need to enable sleep() API for legacy or additional modes?

**Comment by rei-vilo** [comment]
@measley

With EMT, by default, idle mode, *i.e.* no task running = sleep.

**Comment by robertinant** [comment]
This issue was moved to energia/msp432-core#32
