### ISSUE TITLE
Energia IDE layout breaks on 4K and high resloution displays

### ISSUE THREAD

**Issue by measley** [energia/Energia#748]
I got a report at a workshop that on high resolution monitors Energia IDE layout doesn't look right. I don't have one myself so can't reproduce. 

Another related layout bug is when you increase the font under the preferences, the cursor doesn't always match up with the line that is being edited.

**Comment by rei-vilo** [comment]
Which operating system?

Does the same issue affect the Arduino IDE?

**Comment by rei-vilo** [comment]
Maybe related to #730.

**Comment by rei-vilo** [comment]
Without more specifics, we can investigate this issue.
