### ISSUE TITLE
Implement Watchdog for Energia MT-Supported Boards

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#782]
Implement watchdog for the boards supported by EMT.

HAL is provided by `Energia.app/Contents/Resources/Java/hardware/emt/ti/drivers/Watchdog.h`.

Unlike the other RTOS elements proved in the [Galaxia](https://github.com/rei-vilo/GalaxiaLibrary) library, each platform has watchdog-related specifics under the `Energia.app/Contents/Resources/Java/hardware/emt/ti/drivers/watchdog folder`.

* `WatchdogCC26XX.h`
* `WatchdogCC3200.h`
* `WatchdogMSP430.h`
* `WatchdogMSP432.h`
* `WatchdogTiva.h`

**Comment by rei-vilo** [comment]
Two cases:

* TM4C129 fails to connect to Ethernet LAN
* CC3200 fails to connect to WiFi LAN

**Comment by robertinant** [comment]
This issue was moved to energia/msp432-core#33
