### ISSUE TITLE
Test HD44780 LiquidCrystal Library for platforms other than MSP430 = Tiva C Series + MSP432

### ISSUE THREAD

**Issue by robertinant** [energia/Energia#803]
Right now the LiquidCrystal Library is only visible for MSP430. Testing needs to be done for the other platforms so that it can be included for those platforms as well.

**Comment by fmilburn3** [comment]
I have tested it with "Hello World" on the MSP432 and the TMC123GXL successfully.  See this post:  http://forum.43oh.com/topic/9186-hello-world-using-coglcd/?p=69914

**Comment by KingZuluKing** [comment]
Hey guys, does anyone know if there is a liquid Crystal library  for HD44780 displays which works with tm4c 129EX launchpad?

**Comment by rei-vilo** [comment]
Please check on the 43oh forum.

**Comment by KingZuluKing** [comment]
thanks, by the way, what do you think a msp430 library of the same LiquidCrystal will not work on tiva -tm4c 129Xl launchpad? if I import it into suitable folder. Because I did the same for C2000 Piccolo Launchpad, and it worked without any issue.

**Comment by rei-vilo** [comment]
See https://github.com/energia/Energia/issues/803#issuecomment-166010139, if it works on TM4C123, it will work on TM4C129.

**Comment by KingZuluKing** [comment]
checked right now, drops the following errors... maybe you can see something i am mising out here



--------------------------------------------------------------------------------
sketch_aug05a.cpp.o: In function `setup':
sketch_aug05a.cpp:(.text.setup+0x8): undefined reference to `LiquidCrystal::begin(unsigned char, unsigned char, unsigned char)'
sketch_aug05a.cpp.o: In function `_GLOBAL__sub_I_lcd':
sketch_aug05a.cpp:(.text.startup._GLOBAL__sub_I_lcd+0x14): undefined reference to `LiquidCrystal::LiquidCrystal(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)'
collect2.exe: error: ld returned 1 exit status

**Comment by KingZuluKing** [comment]
Tested , works 100 !

**Comment by robertinant** [comment]
This issue was moved to energia/tivac-core#25
