### ISSUE TITLE
CC430 Support

### ISSUE THREAD

**Issue by zacmanchester** [energia/Energia#81]
Hi,

I've started implementing support for the cc430f5137 chip and the em430f5137rf900 board: http://www.ti.com/tool/em430f5137rf900

Right now the blinking light examples run but it looks like it will take some work to get the timers, ADCs, and USCIs working.  It's in my fork under Branch_CC430_support.

I'm really interested in putting together an RF library for the built in CC1101 core.  Anyone else interested?
- Zac

**Comment by rei-vilo** [comment]
See #912

**Comment by thecameronjones** [comment]
Have any other efforts been started to have native support for the CC430 in Energia?

**Comment by rei-vilo** [comment]
What do you mean by « native support » ?

**Comment by thecameronjones** [comment]
Native support as in Energia will work the CC430 out of the box, instead of having to install a board manually.

**Comment by robertinant** [comment]
http://www.panstamp.com/product/197/

You can load it into the Arduino IDE through the custom board manager URL in you preferences. See the tutorial here: 

https://github.com/panStamp/panstamp/wiki/Installing-panStamp-cores-and-libraries-for-Arduino

**Comment by thecameronjones** [comment]
I need to use the standalone CC430 in a custom PCB. I have tried using their custom arduino boards but it hasn't worked out for me.

**Comment by robertinant** [comment]
You should be able to customize the panStamp core to suite your needs.
To answer your previous question, no, we do not have any plans to enable a CC430 core at this point. If your requirements is < 1GHz then I recommend looking at the CC1310 which is enabled in Energia. On top of that you get TI-RTOS which enables you Multi Tasking,

**Comment by thecameronjones** [comment]
I haven't been able to get panstamp to work with my CC430F5137. Regarding the CC1310, I need it to work at super long range. The CC430 works well with my needs. Does the 1310 also have the 430's capabilities?

**Comment by jpnorair** [comment]
Comparing CC430 to CC1310 is like comparing a bicycle and a Ducati… except in this case the Ducati uses less energy to run.

CC1310 has 10x the computing power and 5x the memory.  The radio core is also maybe 5x superior.  CC1350 has integrated BLE as well, which can allow some pretty interesting applications.  But let’s stick to CC1310 for now.

I’m working on ultra-long range solutions for CC1310.  To a certain extent, so is TI-Norway.  They are continuously improving their long-range mode, but they have other things to work on as well.  In any case, people are working on this.  Check out the “Long Range Mode” for CC1310.

If you want to use TI RTOS, CC1310 is pretty easy to get up and running due to all the sample code.  Not sure if it can run Energia yet.  I’m working to port it to some different vendor-agnostic environments.

Best,
JPN

**Comment by dberenguer** [comment]
Just to add some advantages of CC430 over CC1310, CC430 is cheaper, it
provides a unique ID and it's supported by energia/arduino.

**Comment by spirilis** [comment]
CC1310 provides a unique ID (a whole 802.15.4 64-bit IEEE address, in fact).  Its radio happens to be a heck of a lot more sensitive and with more processing power to do crazy stuff like DSSS at 500KHz w/ convolutional encoding and all that.  But... more expensive.

**Comment by dberenguer** [comment]
Thanks Eric for the tip. I din't find any reference to that ID when I read
the datasheet last time.



Daniel Berenguer
http://www.panstamp.com

**Comment by spirilis** [comment]
Yeah it's in there but buried a bit.  IIRC the EasyLink TI examples have references to the FCFG (factory config) locations where it resides.

**Comment by jpnorair** [comment]
Yes, CC1310 is suitable for FCC 15.247 in the USA using DSSS.

The cost of implementing FHSS to clear 15.247, or the cost of certifying against 15.249 or 15.231, quite easily offsets the added cost of the CC1310 ICs. 

CC430 is on 180nm and CC1310 is on 90nm.  Their dies are actually comparable in size.  There’s no reason the CC1310 won’t get cheaper and cheaper as it matures.  If you’re planning for the future, it seems to me to be the clearly better choice.

**Comment by spirilis** [comment]
@dberenguer Here's what I'm using in one of my libraries:

	// Ripped from EasyLink: IEEE address location burned into ROM
	//Primary IEEE address location - FCFG (Factory Config) MAC_15_4_0 register represents bits 31:0 of the 64-bit IEEE 802.15.4 address
	#define EASYLINK_PRIMARY_IEEE_ADDR_LOCATION   0x500012F0
	UInt32 *ieeeAddr = (UInt32 *)EASYLINK_PRIMARY_IEEE_ADDR_LOCATION;

	return *ieeeAddr;

My understanding is the full 64-bit address is stored little-endian so the first 4 bytes are the lower 32 bits, second 4 bytes are the upper 32 bits.  My own RF library only uses 32-bit addressing.

**Comment by thecameronjones** [comment]
The CC1310 seems like it might be a good choice, but its RX sensitivity is worse than the CC430's. Just to confirm, I need to use this chip for ultra long-range communication, primarily or entirely with the chip transmitting. I also need to be able to operate with super low power, which the CC1310 does nicely. Finally, I2C, serial, and a small form factor are necessary. For my listed requirements, do you think that the CC1310 best fits my needs? Currently, I have a CC430 mounted on a surfboard and a MSP430G2 Launchpad to program it. If I get a CC1310 on a surfboard, what programmer should I get? I would prefer a low-cost option.

Thank you,
Cameron

**Comment by spirilis** [comment]
What kind of long range?  TI Norway did a test with a pair of CC1310 LaunchPads using LRM mode (0.6kBaud), which is designed for maximum long range minimal bitrate, and got 22km line of sight without any PA/LNA in the middle (using the CC1310's built-in max TX of 14dBm).  That was at 868MHz fyi.

Also I'm not sure where you're getting "RX sensitivity is worse than CC430" from...
CC430 uses a CC1101 inside, CC1101 RX sensitivity is -116dBm at 0.6kBaud - CC1310 LRM at 0.6kBaud is -124dBm.  Looking at an example CC430 datasheet, cc430f5137, it mentions -117dBm at 0.6kBaud, still worse than the CC1310.

**Comment by spirilis** [comment]
Also FYI, I use a CC1310 LaunchPad with a Cortex 10-pin cable to program my custom CC1310 boards.  The newer ARM LaunchPads (CC1310, CC1350, CC2650, newer red MSP432) include a CMSIS-DAP compliant "XDS110" FET onboard which can be used to program all the TI ARM Cortex-M devices over SWD.  So the lowest-cost option for programming a CC1310 is to buy an MSP432 LaunchPad, but of course if you have some CC1310 or 1350 LaunchPads they can be used out of the box to program your external projects.

I personally splurged the $40 for a Tag-Connect 6-pin cable (with the 50mil 2x5 Cortex connector on the other end), but you can use a 50mil 2x5-to-50mil 2x5 cable, or use standard 100mil jumper wires between the jumper block and your board.

**Comment by spirilis** [comment]
As for Eagle, maybe ask on the E2E Sub-1GHz forum if someone has a footprint... I also am aware TI offers some sort of files compatible with "Ultra Librarian" to generate footprints in different packages... I used a free d/l version of it to produce DipTrace libraries (had to edit them a bit, but I've used it successfully with my custom boards).

**Comment by thecameronjones** [comment]
@spirilis Thanks for the info! I seemed to have misread the datasheets about the RX sensitivity. I just want to confirm that [this Launchpad](https://www.amazon.com/LaunchPad-MSP-EXP432P401R-breadboard-wires-bundle/dp/B012E9J65Y/) sold on Amazon is the one you were referring to and would work with the Serial Wire Debug protocol to program the CC1310. You mentioned the "newer red MSP432", this one is black but I'm not sure what the difference is. By ultra-long range, I mean a much farther distance than for what its intended for; on the scale of 100s of kilometers rather than 10s. Although it is not intended for this distance, through transmitting at a low frequency, having a sensitive receiver with high gain, and utilizing CDMA, I believe that it is feasible to transmit and receive a kb in a few minutes. Also, what is the difference between the CC1310F128RGZT and the CC1310F128RGZR?

Thanks for your help,
Cameron

**Comment by spirilis** [comment]
@thecameronjones I couldn't know if the LP on that link is the new red type.  I do know the old black ones don't have the standard 50mil Cortex SWD connector and moreover, its version of the MSP432 won't be supported in the future.  Probably safest to buy from TI store for the MSP432 LP right now.

**Comment by spirilis** [comment]
Fyi- TI store has free shipping thru end of this year "FALLFREESHIP" (saw on 43oh.com)

**Comment by thecameronjones** [comment]
@spirilis Thanks, is it possible that you could link me to both of the cables you mentioned? I can't seem to find them on Tag Connect.

**Comment by spirilis** [comment]
Ribbon cable (would require your board has the 50mil Cortex SWD male header soldered on): http://www.tag-connect.com/CORTEXRIBBON10

Tag-Connect TC2030 w/ legs for SWD: http://www.tag-connect.com/TC2030-CTX

Tag-Connect TC2030-NL (no legs) for SWD: http://www.tag-connect.com/TC2030-CTX-NL (this is what I use, minimal footprint with no soldered components required, but you have to hold it on with your hand unless you have a jig on the bottom to clamp the thru-pins--Tag Connect sells some board contraption for doing that)

**Comment by thecameronjones** [comment]
@spirilis I have used JTAG before, but not SWD. Am I correct in that SWD requires VCC, GND, TX, RX, TMS, TCK, and RST to program and serially communicate with the chip?

**Comment by spirilis** [comment]
No TX/RX and technically the UART pins aren't broken out.  Likewise the launchpad FTSH connectors (those 50mil 2x5) don't have UART lines and Tag Connect's footprint doesn't include it either.

Otoh, TI has the CIO console interface over JTAG for printing some debug info, but it can significantly pause the CPU and impact the code.  Useful in a pinch though.  If verbose debug I/O is required just include some 100mil headers on your board for junpering over to the LaunchPad's UART TX/RX lines in addition to JTAG.

**Comment by spirilis** [comment]
Incidentally, I believe there is a JTAG "mailbox" system one could use for debugger I/O but TI doesn't use it and I'm not sure if the CCS debugger can work with it.  TI's CIO method has been around for a long time so I'm guessing that's why they use it even on ARM Cortex-M.

**Comment by thecameronjones** [comment]
So, to use Serial input/output, I should just connect up the SWD pins for programming and use jumpers for the RX/TX, correct? Also, other than a difference in the number IO pins, is there a big differentiator between the 32 and 48 pin versions of the CC1310?

**Comment by spirilis** [comment]
What I mean is the Tag-Connect 6-pin connector doesn't have any UART stuff - http://www.tag-connect.com/Materials/TC2030-CTX.pdf - and the Cortex SWD connector doesn't seem to spec it either.

You are correct in that TI has standardized on their own RTOS for software developed on the CC1310.  Energia runs on top of the RTOS, in fact they got a start on that whole paradigm with the MSP432 port of Energia.  This might be a little different from CC430 development but thus far I don't think it's all that bad... I've wrapped my head around it enough.  You'll be developing inside an RTOS environment which you can blissfully ignore all you want (by having just a single "main task" that runs all your code, however, hardware interrupts are registered a little differently using TI-RTOS's "Hwi" infrastructure).  I have come to embrace the multithreaded RTOS nature myself and use Mailbox objects and Semaphores a lot to synchronize multiple tasks.  I think it's a boon for sophisticated drivers (having the device driver details "handled by" a separate task).

No the 32-pin version is just missing a few GPIO's from what I understand.

As for other forums, posting further questions on the TI E2E Sub-1GHz forum is probably your best bet.  https://e2e.ti.com/support/wireless_connectivity/proprietary_sub_1_ghz_simpliciti/

**Comment by thecameronjones** [comment]
@spirilis I think I now have a good understanding of how I will be able to set up the CC1310. The final issue for me is using the TI-RTOS and programming the chip to transmit. If you have any code examples/resources that you could point me to, that would be very helpful. Any examples that show how using RTOS and the radio makes developement different would be useful. I plan to write all my code in Energia, so if there are libraries that make interfacing with the radio easier, I would definitely want to use them. 

Thanks,
Cameron

**Comment by spirilis** [comment]
Energia should abstract most things for you.  Energia MT (the RTOS version) lets you declare multiple threads by having multiple source files with prefixed versions of "setup" and "loop" functions.  Look at the MSP432 implementation for more info.

I believe @robertinant plans to include a C++ wrapper lib atop the TI EasyLink code to make radio usage easy to access.

**Comment by thecameronjones** [comment]
Can the threads interact with each other in Energia?

**Comment by spirilis** [comment]
Sure, ask @rei-vilo about his Galaxia library for making the TI-RTOS synchronization facilities easy to use.

**Comment by thecameronjones** [comment]
@spirilis I am not experienced with creating Eagle libraries, but after half an hour and some googling I have produced a rough library for the CC1310. If you could take a look and confirm that the SMD footprint works properly, I would be happy to share this with the community so others in the future don't have to do this. Attached is the zipped .lbr file.
[CC1310F64RHB.lbr.zip](https://github.com/energia/Energia/files/561264/CC1310F64RHB.lbr.zip)

Thanks,
Cameron

**Comment by spirilis** [comment]
No idea, I am not an Eagle user.  Perhaps some folks at 43oh.com would be able to look?

**Comment by rei-vilo** [comment]
@thecameronjones For details about the Galaxia library, please visit http://embeddedcomputing.weebly.com/exploring-rtos-with-galaxia.html

**Comment by robertinant** [comment]
@thecameronjones the EasyLink library is available in the Energia library manager under Sketch->Include Library->Manage Libraries. Then search for EasyLink. There are 2 examples included for the library. One for TX and one for RX.

**Comment by thecameronjones** [comment]
@rei-vilo @robertinant Very helpful, thanks.

**Comment by thecameronjones** [comment]
@spirilis Are there any other alternatives to connecting the UART pins? Optimally I want to have only 4 pins connected (VCC, GND, TMS, TCK). Does Energia work with the CIO console interface? My goal is to make it as easy as connecting the 4 pins and opening the serial monitor in Energia (although I recognize that this is probably impossible). Also, can you confirm that the RESET_N pin in not needed for the programming and debugging of the CC1310?

Thanks,
Cameron

**Comment by robertinant** [comment]
@thecameronjones,

1. Energia does not support CIO. UART is your only option at this point.
2. Good question, the standard 10 pin ARM header calls for RST. Not a JTAG expert so I just pulled the reset pin jumper of the CC1310 LaunchPad and that failed. As per this unscientific experiment I am guessing, yes, it does need RST.
3: For Energia, it follows the BoosterPack standard (https://www.ti.com/ww/en/launchpad/dl/boosterpack-pinout-v3.pdf) SDA is on pin 10 and SCL is on pin 9.

**Comment by thecameronjones** [comment]
@robertinant Thanks for the info. Would it be possible to put a bootloader on the CC1310 so I could program it and use serial communication with only the UART pins? Also, for Energia, are the I2C pins user definable? Thanks.

**Comment by spirilis** [comment]
@thecameronjones Looks like there may be one in ROM already - http://www.ti.com/lit/an/swra466a/swra466a.pdf

**Comment by cameronus** [comment]
@spirilis According to post on a forum I read, it may be better to create a secondary bootloader, therefore reducing the risk of completely bricking the chip. In addition, I wouldn't know how to access this bootloader.

**Comment by spirilis** [comment]
Yeah up to you, but, the main problem is what happens if the CCFG area gets corrupted during load; IIRC, you can just use JTAG to reflash it.  So long as you have JTAG broken out you can use CCS and a LaunchPad to recover it in the event that happens.  My guess is this is a big deal for truly remote installations that need in-the-field updates...

**Comment by cameronus** [comment]
@spirilis Would you know how to set up a bootloader like this? I can't find much information about it in the TI docs.

**Comment by spirilis** [comment]
I don't have any experience messing with bootloaders, sorry.  Looks like you need to be able to reset the board, hold a GPIO high or low (and that GPIO# along with the high/low setting needs to be in the CCFG config word for the bootloader), and then talk the bootloader protocol over the serial port.  So those points need to be considered when choosing the hardware you're using to talk with it.

**Comment by cameronus** [comment]
@spirilis @robertinant Does Energia allow me to manually set the I2C pins?

**Comment by cameronus** [comment]
@spirilis @robertinant Does anyone have a minimum circuit for using the basic functionality of the CC1310 and its radio?

**Comment by spirilis** [comment]
@cameronus It's very important that you follow the TI designs (unless you're an analog & RF expert and know what you're doing).  FCC/ETSI qualification and conformance related to antenna performance & emissions is the reason.  Look for details on the CC1310 product page (www.ti.com/product/cc1310).  Please use the E2E Sub-1GHz forum for further questions on this matter.

**Comment by jpnorair** [comment]
Especially follow their designs on the DC-DC part.  DC-DC noise is a problem for RF.  The rest of it, you have some leeway.  

Also, Johanson makes an integrated Balun for CC1310.  I recommend using this if you are doing a single-ended antenna.  TI has an app note.

**Comment by cameronus** [comment]
I have wired up my CC1310 surfboard using jumper cables to the 2x10 header on the MSP432. I have VDDS, VDD2, GND, TMS, TCK, and RST connected. I have doubled-checked the placement of all connections. I am using the CC1310 board in Energia and I am trying to upload a simple Blink example. The error log is [here](https://gist.github.com/cameronus/671a0ceb1318333240c6e63bad389ea9). I'm not sure what's happening. Does it allow any of you guys come to a quick conclusion such as the wiring is bad or there is an issue with the board? If not, I'll post elsewhere. I just thought it would be quick to check here.

**Comment by robertinant** [comment]
As far as I know, you will need GND, VCC, TMS, TCK, TDO and TDI. Also make sure that you remove those jumpers from the MSP432 LaunchPad programming header. It would probably be better to jumper them from the actual programmer / to LaunchPad headers.

**Comment by cameronus** [comment]
I'll try adding TDO and TDI. What do you mean by "It would probably be better to jumper them from the actual programmer to LaunchPad headers?" Do you mean I should buy a 2x5 pin cable to connect to the programmer's J102?

**Comment by cameronus** [comment]
@robertinant I have wired all necessary power pins as well as TDO and TDI. There is a new error which I am getting which can be found [here](https://gist.github.com/cameronus/9ff981c1daabdccd80c688d74251812c).
