### ISSUE TITLE
min() and max() not declared with EMT CC3200 & MSP432

### ISSUE THREAD

**Issue by kingofl337** [energia/Energia#815]
When using EMT version of the CC3200 calling min() and max() results in a unknown declaration, using non-emt board works fine.

code
void setup()
{
  // put your setup code here, to run once:
  
}

void loop()
{
  // put your main code here, to run repeatedly:
  int x = min(3,5);
  int y = max(5,7);
}

sketch_jan02c.ino:14:18: error: 'min' was not declared in this scope
sketch_jan02c.ino:15:18: error: 'max' was not declared in this scope

**Comment by rei-vilo** [comment]
See #815

**Comment by robertinant** [comment]
Thanks for the report!
This has been fixed and will be in the next release.
For now you can work around it by adding the macros at the top of your Sketch.
```
#define min(a,b) ((a)<(b)?(a):(b))
#define max(a,b) ((a)>(b)?(a):(b))
```
