### ISSUE TITLE
Implement IR (send/receive) library

### ISSUE THREAD

**Issue by pbrier** [energia/Energia#82]
There is currently no IR send/receive functionality

For arduino, see:
http://www.pjrc.com/teensy/td_libs_IRremote.html

or

http://www.arcfn.com/2009/08/multi-protocol-infrared-remote-library.html

**Comment by mckargaci** [comment]
hello everyone

I want to use  IRremote library and its receive demo example for MSP430F5529 LP. The IRrecvDemo example and the others don't work  with MSP430F5529 LP.
 
when l download IRrelay.ino example to my MSP430F5529 LP and push my NEC remote control button, l receive this massage on my serial monitor.
 
Could not decode message
Raw (60): 11796 8900 -4200 550 -1500 550 -550 500 -500 550 -550 500 -1550 500 -550 500 -550 500 -500 550 -500 550 -500 550 -500 550 -500 550 -500 550 -500 500 -500 550 -550 500 -550 500 -1550 550 -500 550 -500 550 -450 600 -500 550 -500 550 -500 550 -500 500 -1600 500 -500 550 -500 500 
 
what do you think about why MSP430F5529 LP does not know NEC protocol?

**Comment by rei-vilo** [comment]
May I suggest to post your question at the 43oh forum at http://forum.43oh.com?
