### ISSUE TITLE
Is there any plan to translate the interface?

### ISSUE THREAD

**Issue by cjdg** [energia/Energia#824]
Hi i been using energia for some courses for kids, but i was wondering if there is a plan to start to translate energia to other langs? :)

**Comment by cjdg** [comment]
I forgot i would like to collaborate to spanish language :)

**Comment by rei-vilo** [comment]
Presently, the Energia IDE is based on Arduino IDE 1.0.1.

Should Energia move to Arduino 1.6.5, the Arduino IDE 1.6.5 already includes translations.

See Update the IDE to release 1.6.7 of Arduino #588.
