### ISSUE TITLE
Curser goes wrong after changing font size

### ISSUE THREAD

**Issue by hank205** [energia/Energia#864]
I'm using Energia(0101E0017) on MacOSX10.11.3.
After I change the font size(either bigger or smaller), the curser goes wrong:
1) Double tapping the mouse hight lights the wrong field.
2) The curser is displayed at the wrong place on the screen. (off by 3 chararacters)
Demonstrated below by pressing the delete button:
![energia_bug](https://cloud.githubusercontent.com/assets/8160008/13836726/425e2760-ebd2-11e5-9894-7512fca8ec8c.gif)

Restarting the software will make the new font size work, but still fail after changing font size again.

Steps to reproduce the bug:
1)open Energia and load a file(mine is using File->Examples->01.Basics->Blink)
2)change font size(Energia->Preferences->Edit font size). 
Initially, font size is 10. I found the bug after I changed font size to 14.

**Comment by rei-vilo** [comment]
Next release of Energia will be based on Arduino 1.6.x.

**Comment by rei-vilo** [comment]
Which OS please?

**Comment by hank205** [comment]
MacOSX10.11.3
