### ISSUE TITLE
MSP430 Toolchain does not work on Windows with Spaces in the Path / Username

### ISSUE THREAD

**Issue by nmaas87** [energia/Energia#876]
Dear Energia Team,

I know the error that nearly all Toolchains do not work on Windows if the Path contains a space is well known, but there has been no real fix at the moment, and I did not see an open issue for that.
Could you please fix that bug?

( I came over from platformIO which uses Energia - Issue is here: https://github.com/platformio/platformio/issues/493)

Thanks a lot

**Comment by rei-vilo** [comment]
Unfortunately, this is not a limitation specific to Energia, but due to the underlying tools, namely the GCC tool-chain. 

All Processing-based Wiring-derived Arduino-like IDEs suffer form the same issue on Windows. 

Sorry.
