### ISSUE TITLE
IPAddress bytes stored in wrong order

### ISSUE THREAD

**Issue by kimling** [energia/Energia#883]
I noticed that when I called IPAddress& IPAddress::operator=(uint32_t address) function, using value 3232235633 (192.168.0.113), the stored IP address is 113.0.168.192.

**Comment by kimling** [comment]
I made quick fix like this to solve this issue for now

`IPAddress& IPAddress::operator=(uint32_t address)`
`{`
   ` _address[0] = (address & 0xff000000) >> 24;`
   ` _address[1] = (address & 0xff0000) >> 16;`
   ` _address[2] = (address & 0xff00) >> 8;`
    `_address[3] = (address & 0xff);`
    `return *this;`
`}`

**Comment by rei-vilo** [comment]
Same happens with some Arduino boards.
