### ISSUE TITLE
0165E0018 Version Number

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#889]
File `/Applications/IDE/Energia-18.app/Contents/Java/lib/version.txt` in charge of the version number contains `1.6.10B2` instead of `0101E0017` for previous versions.

Do you plan to keep the same versioning scheme? 

I strongly suggest to do so. In that case, version number should be **`0165E0018`**.

**Comment by robertinant** [comment]
Actually, this version number should be 1.6.10E0018Bx or 1.6.10E0018 for the final release. This is an input when calling ant dist. So I will make sure that I put in the right version when building the beta/release.

**Comment by rei-vilo** [comment]
Latest release of Arduino.CC IDE is 1.6.9.

The `/Applications/ArduinoCC.app/Contents/Java/lib/version.txt` file says `1.6.9` but the parameter passed on to the compiler is `-DARDUINO=10609`. 

Dealing with `10609`is easier than dealing with `1.6.9`.

Up to you for the final choice.
