### ISSUE TITLE
0165E0018 Library Management

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#892]
One test with library management didn't succeed with the `.json` file at https://raw.githubusercontent.com/rei-vilo/ReiVilo_Libraries_Index/master/ReiVilo_Libraries_Index.json

**Comment by robertinant** [comment]
Unfortunately as per the FAQ quote you mentioned, there is only one library_index.json for now. Supposedly the Arduino team is working on enabling third party URL's just like with the board manager. I will wait for that implementation and pull it into Energia when available.

For now, I will add your libraries to the centralized library_index.json file.

**Comment by rei-vilo** [comment]
Great!
