### ISSUE TITLE
0165E0018 Installing and Updating Library Fail

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#895]
Both Installing and updating library fail, here with the WiFi library.

<img width="800" alt="capture 2016-06-10 a 11 35 00" src="https://cloud.githubusercontent.com/assets/951776/15960330/97bfb938-2eff-11e6-80a5-b39a2c3032ea.png">

**Comment by robertinant** [comment]
This was a test library_index.json that I posted to see if a updated library would show up. This library_index.json is not final yet and thus closing this issue.
