### ISSUE TITLE
0165E0018 Wrong Icon for Sketches

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#897]
On Mac OS X , the icon for sketches located at `/Applications/Energia.app/Contents/Resources/pde.icns`  displays the Arduino logo...

![no](https://cloud.githubusercontent.com/assets/951776/16035648/83046a22-3218-11e6-984c-26553054c0d2.jpg)

...instead of the Energia logo.

![yes](https://cloud.githubusercontent.com/assets/951776/16035649/83311900-3218-11e6-824f-0db39b40a39f.jpg)

I haven't checked the Window and Linux variants.

**Comment by robertinant** [comment]
Fixed with 3658436bf7d609bf9afb46b691f3bee24b7976a1
