### ISSUE TITLE
0165E0018 MSP430 Core Multiple Locations and Possible Conflicts

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#898]
Energia suggested to install a package for the MSP430.

<img width="400" alt="capture 2016-06-15 a 14 21 01" src="https://cloud.githubusercontent.com/assets/951776/16079885/0d32ef1e-3306-11e6-982d-0c55ec0c6ee9.png">

As a result, the MSP430 core folder has multiple locations:

* Common folder `/Applications/Energia.app/Contents/Java/hardware/energia/msp430`
* Specific folder under `~/Library/Energia15/packages/energia/hardware/msp430/1.0.1`

Only one board is available, `MSP430F5529`.

<img width="400" alt="capture 2016-06-15 a 14 27 43" src="https://cloud.githubusercontent.com/assets/951776/16079844/c033fe10-3305-11e6-8239-a42c22e2f5a7.png">

**Comment by rei-vilo** [comment]
Arduino.CC / Genuino experimented with similar solution on release 1.6.6 (AVR platform under specific folder `~/Library/Arduino15/packages/arduino/hardware/avr/1.6.9`) but went back on release 1.6.7. to common folder (AVR platform under common folder `/Applications/Arduino.app/Contents/Java/hardware/arduino/avr`).

I suggest to split the MSP430 into 2 platforms: 

* **MSP430G2** under common folder `/Applications/Energia.app/Contents/Java/hardware/energia/msp430g2`,  as this MCU shouldn't evolve much.
* **MSP430F** under specific folder `~/Library/Energia15/packages/energia/hardware/msp430f/1.0.1`

**Comment by robertinant** [comment]
I was working on the MSP430 core and that triggered your beta version not to recognize the builtin one anymore. The issue was that the version number in package_index.json was not correct. I'll get you a new beta.
