### ISSUE TITLE
Static code can not configure pins on MSP432

### ISSUE THREAD

**Issue by dronus** [energia/Energia#901]
Even if pure libraries (only using the Arduino / Energia API) are used, some of them show odd behavior on the MSP432.

For example, the LiquidCrystal library only works on certain pin numbers, while crashing the MCU on others. 

It however works well, if it is modified to do all pin initalisation (like pinMode) in begin(), so that it is actually called by setup(). 

I guess the static initalisation is invoked to early, calling pinMode and digitalWrite before device specific initalisation code is ready.

Either it should be discouraged for any library to do static initalisation despite variables, or the init code should be modified to handle this situation, eg. the GPIO subsystem initalised before any setup of the main code is made, including static initalizers.

**Comment by robertinant** [comment]
This issue was moved to energia/msp432-core#8
