### ISSUE TITLE
Provide more configurable Serial.begin variants

### ISSUE THREAD

**Issue by dronus** [energia/Energia#903]
It would be nice if bitcount, stopbit and parity would be configurable by `Serial.begin`.  

While Arduino libraries may be hacked to use different settings, the more complex controllers like MSP432 are using precompiled libraries and it is almost impossible to change those settings. 
This is sad as some peripherial hardware require different settings.

For most UARTs used by `HardwareSerial`, this settings are easily applied.

**Comment by rei-vilo** [comment]
Linked to #835.

**Comment by robertinant** [comment]
This issue was moved to energia/msp432-core#6
