### ISSUE TITLE
Support for Wiring's Vector class?

### ISSUE THREAD

**Issue by wulftone** [energia/Energia#904]
I've got an MSP432P401R and I'd love to use the `Vector` class from the Wiring framework.  Alas, my C++ skills are minimal at best so I'm not sure how to include it.  I don't see it in Energia's source, although there are other pieces of Wiring available.  How can I go about getting `Vector`?

**Comment by rei-vilo** [comment]
The `vector` class is a standard C/C++ library.

**Comment by wulftone** [comment]
Interesting, so why does wiring have one in their lib? More importantly, how can I use the standard one?

**Comment by rei-vilo** [comment]
Please post your question at the [Energia section of the 43oh forum](http://forum.43oh.com/forum/119-energia/).
