### ISSUE TITLE
Use dslite to program more than one tiva on a usb hub 

### ISSUE THREAD

**Issue by blueminerals** [energia/Energia#917]
I work with 6 tiva boards on a usb hub and I need to flash the same program to all of them frequently. Unplugging usb cables is tedious. Energia18 seems to default to the last usb port in the com port list. Is there some way alter dslite to program by selected com port or board serial number?

**Comment by rei-vilo** [comment]
Have you tried working on the Energia sketch with CCS?

**Comment by robertinant** [comment]
This issue was moved to robertinant/EnergiaNG#19
