### ISSUE TITLE
MSP430F5529 : undefined reference to `operator new[](unsigned int)'

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#918]
Using `new` against the MSP430F5529 raises an error.

```
undefined reference to `operator new[](unsigned int)'
```

Maybe [energia/msp430-ng-core](https://github.com/energia/msp430-ng-core) will support it?

_Cross posted with https://github.com/energia/msp430-lg-core/issues/15_
_Cross posted with https://github.com/energia/msp430-ng-core/issues/2_

**Comment by robertinant** [comment]
Will use the issue reported against the msp430-lg-core to address this.
