### ISSUE TITLE
Where to Post Issues for Energia 1.6.10E18?

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#919]
Where to post issues for Energia 1.6.10E18?

* here
* at [robertinant/EnergiaNG](https://github.com/robertinant/EnergiaNG/issues)
* at the respective MCU repositories

Thank you!

_Corse poste with https://github.com/robertinant/EnergiaNG/issues/18_

**Comment by robertinant** [comment]
Please post any IDE issues in the EnergiaNG repo. Anything related to the cores should be posted in the MCU repos.

**Comment by rei-vilo** [comment]
Thanks!
