### ISSUE TITLE
PFatFs for CC3200EMT

### ISSUE THREAD

**Issue by omidathari** [energia/Energia#924]
Hi Is there a different library of PFatFs for the CC3200EMT as opposed to CC3200.
thanks in advance

Adam

**Comment by robertinant** [comment]
As far as I know the PFatFs should work on the EMT version? What issues are you running into?

I'll move this issue to the tivac-core so that we can keep track or it there..

**Comment by robertinant** [comment]
This issue was moved to energia/tivac-core#11
