### ISSUE TITLE
Latest energia doesnt have 2231 or 2452 on board selector

### ISSUE THREAD

**Issue by cjdg** [energia/Energia#930]
I downloaded the latest version (18) and cannot see the 2231 or 2452  MCU on energia on the board selector

**Comment by RickKimball** [comment]
Duplicate issue see here:

https://github.com/robertinant/EnergiaNG/issues/7
and here:
https://github.com/energia/msp430-lg-core/pull/2
and here:
https://github.com/energia/Energia/issues/922
