### ISSUE TITLE
I2C configure with Energia

### ISSUE THREAD

**Issue by duyka0110** [energia/Energia#933]
Hi guys.
 
I'm currently learning I2C with Energia on LM4F120 but i can't figure a way to setup which I2C pin use for communication, since the microcontroller has 4 I2C pair pins.

So how exactly can I manage to do that?

Thanks very much

**Comment by rei-vilo** [comment]
Use `Wire.setModule()`.

Should be added to the [Wire Library (I²C) reference page](http://energia.nu/reference/wire/).

**Comment by rei-vilo** [comment]
See #934.

**Comment by duyka0110** [comment]
thanks very much, appreciate it
i will try
