### ISSUE TITLE
I2C device at any address LM4F120

### ISSUE THREAD

**Issue by duyka0110** [energia/Energia#935]
I'm learning about I2C and practicing on the LM4F120 board, I'm using DS1307 as the I2C device.
But when I try to find which I2C device is currently on the bus, I get I2C device found at any address.
I did checked my wire connection, my I2C port setModule() setup, etc but still.
This does not happen with Arduino board.
Please help me out. Thank you very much.

**Comment by rei-vilo** [comment]
Please visit the [43oh.com](43oh.com) forum and search for DS1307. You'll find many answers!

This repository focuses on reporting bugs with Energia rather than issues with projects.

Thank you.

**Comment by duyka0110** [comment]
okay thank you
