### ISSUE TITLE
Where are pin definitions for MSP432?

### ISSUE THREAD

**Issue by alkhimey** [energia/Energia#937]
I downloaded Energia from the website, version 1.6.10E18 and am unable to reference P2_5, P2_6 etc.

```'P5_2' was not declared in this scope```

Looking at the code in the repository, it looks like these definitions are missing from hardware/msp432/cores/msp432.

**Comment by rei-vilo** [comment]
Use pins numbers instead, like `12` for `P5_2`.

See [Pin Naming](http://energia.nu/pin-maps/) and [LaunchPad MSP432 Pins Map](http://embeddedcomputing.weebly.com/msp432-launchpad-pins-maps.html)
