### ISSUE TITLE
Compiler not found for TivaC package - Linux64

### ISSUE THREAD

**Issue by ricardojlrufino** [energia/Energia#939]
When you download the core for Tiva, and use the Stellaris Board, I found that the compiler was not in the variable / path
I need edit:

> /home/ricardo/.energia15/packages/energia/hardware/tivac/1.0.2/platform.txt

And add:

> runtime.tools.arm-none-eabi-gcc.path=/home/ricardo/.energia15/packages/energia/tools/arm-none-eabi-gcc/4.8.4-20140725

**Comment by rei-vilo** [comment]
Could you please confirm the release of Energia is 1.6.10E18?

**Comment by ricardojlrufino** [comment]
Yes, its 1.6.10E18

**Comment by rei-vilo** [comment]
See https://github.com/energia/tivac-core/issues/14

**Comment by robertinant** [comment]
This issue was moved to energia/tivac-core#23
