### ISSUE TITLE
BLE library

### ISSUE THREAD

**Issue by github4f** [energia/Energia#940]
Hi- I would like to use CC2650 (BoosterPack) in network processor configuration, and  MSP432 as the application processor. However, I faced three issues as explained bellow. I appreciate your comment. tnx

1) I can find the Simple Network Processor Image, however I need to modify the source code for my application. Is there any link for it?

2) I found the enegia BLE library very great. However, I designed my own msp432 board (somehow different from laucnpad) and I now would to write the application in embedded c (instead of enegia). I was wondering how I can use the enegia BLE library in embedded c? 

3) Finally, I am wondering how enegia BLE library controls the network processor? Does it rely on at command? is there any at command firmware for cc2650? 

Thanks and regards,

**Comment by robertinant** [comment]
You should be able to find the answers to your questions here: http://www.ti.com/tool/boostxl-cc2650ma

Robert
