### ISSUE TITLE
Location of WiFi UDP library code in the directory?

### ISSUE THREAD

**Issue by wengchen1993** [energia/Energia#944]
Hi, I am fairly new to Energia and want to try implement the UDP multicast function in the Wifi UDP library. I downloaded Energia from the official website but have no clue where the Wifi UDP library .h file and .cpp files are located. Can someone please kindly point it out for me? 

(Only WiFi UDP files I found are in the energia-1.6.10E18/hardware/energia/msp430/libraries/WiFi directory and editing them doesn't have any effect. Currently running Energia on CC3200)

**Comment by StefanSch** [comment]
Have a look into this thread it lists path for the various operating systems:
https://github.com/energia/cc3200-core/issues/5#issuecomment-262907040

**Comment by rei-vilo** [comment]
Feel free to post your question at the 43oh.com forum.
