### ISSUE TITLE
Allow access to pins not on Launchpad

### ISSUE THREAD

**Issue by Tejp1996** [energia/Energia#945]
Microcontrollers such as the MSP are very commonly embedded into custom PCBs. Energia is a great platform for debugging/testing, and even for full deployment. However, because only launchpad pins are accessible, that makes a lot of pins unusable for these things. 

In my case, the MSP430F5529 has tons of pins that are not accessible on the launchpad headers that are being used on a custom PCB. Maybe I'm missing something?

**Comment by rei-vilo** [comment]
Energia focuses on the LaunchPads and BoosterPacks. 

For using the full potential of the MCUs, please consider [Code Composer Studio](http://www.ti.com/tool/ccstudio).

**Comment by Tejp1996** [comment]
They could easily be added to the list of launchpad pins in addition. CCS is not as easy to prototype with as Energia. Energia doesn't have to shift focus from LaunchPads. Im sure many others will find this useful.

**Comment by rei-vilo** [comment]
Please see Getting Started Guide for Developers #907.
