### ISSUE TITLE
OS X. Launch icon looks ugly.

### ISSUE THREAD

**Issue by adevua** [energia/Energia#948]
Please, correct the icon. There are bad things on the sides, pixels are clipped not in the grid.

**Comment by rei-vilo** [comment]
Icon looks perfect on my MacBook.

<img width="78" alt="capture 2016-12-17 a 22 16 16" src="https://cloud.githubusercontent.com/assets/951776/21289809/7d5a3310-c4a6-11e6-9099-f88935fff12e.png">

**Comment by adevua** [comment]
Please, check not on the white back. Look at Launchpad. Users (pixel perfect addicted persons) with Retina display will see it. Will be great to have an ideal icon. I know we can live with it.
