### ISSUE TITLE
OS X. Updated Launch icon. (Pixels blurred. Fixed.)

### ISSUE THREAD

**Issue by adevua** [energia/Energia#950]
Please, check and possibly update the package. This should look much better on our screens. 

[icons.zip](https://github.com/energia/Energia/files/659200/icons.zip)
[processing.zip](https://github.com/energia/Energia/files/659201/processing.zip)

**Comment by rei-vilo** [comment]
Duplicate with #948.

**Comment by adevua** [comment]
Will be great to have an ideal icon in the next Energia releases. 

![379e2e2c-c4af-11e6-8a3e-751aced890c8](https://cloud.githubusercontent.com/assets/6237239/21321438/7fe438f6-c61d-11e6-9432-f3ee64d41ade.png)

**Comment by robertinant** [comment]
Thanks for the icons. Will for sure included them in the next release.

**Comment by robertinant** [comment]
This issue was moved to robertinant/EnergiaNG#24
