### ISSUE TITLE
Add I2C ports in MSP432 with energia

### ISSUE THREAD

**Issue by danielrikmed93** [energia/Energia#951]
Hello,

How can I'm add other I2C ports in Energia 18, I want to use the 2 and 3 pins of the MSP432

**Comment by rei-vilo** [comment]
Have a look at documents [msp432p401r](http://www.ti.com/lit/gpn/msp432p401r) and [slac698f](http://www.ti.com/general/docs/lit/getliterature.tsp?baseLiteratureNumber=SLAC698&fileType=zip) but you would need to use CCS.

**Comment by robertinant** [comment]
Currently there is only on Wire available. There is no plan to add additional Wire instances at this point.
