### ISSUE TITLE
Failed to trigger Bootloader

### ISSUE THREAD

**Issue by Prajwal-B-Ainapur** [energia/Energia#959]
I am new to using cc3200 launch xl and while uploading a example program with energia, it displayed the error as shown below. P.S. the D2 LED which is supposed to glow when it is uploading is always on. Any idea on why this occurs

Sketch uses 6,600 bytes (2%) of program storage space. Maximum is 262,144 bytes.
Opening COM4
Triggering bootloader....
Trigger bootloader failed. Retrying... (1 attempt)
Trigger bootloader failed. Retrying... (2 attempt)
Trigger bootloader failed. Retrying... (3 attempt)
Trigger bootloader failed after 3 attempts
Failed to trigger bootloader
An error occurred while uploading the sketch

**Comment by rei-vilo** [comment]
See http://embeddedcomputing.weebly.com/launchpad-cc3200-wifi.html and http://energia.nu/cc3200guide/

![2978393_orig](https://cloud.githubusercontent.com/assets/951776/23333758/93e3fa04-fb91-11e6-8ab4-963108f3117b.png)
