### ISSUE TITLE
Error returning NaN

### ISSUE THREAD

**Issue by denzelwamburu** [energia/Energia#970]
Am developing in the following environment, 
`LaunchPad_msp430f5529`

`1.6.10E18`

`OSX11.11`

and i can't seem to pass or return a NAN value successfully.
The following error is returned.
`error: 'NAN' was not declared in this scope`

Is there anything extra am supposed to include?

P.S: I've tested the same code in Arduino and it works just fine.

**Comment by rei-vilo** [comment]
The Macro: float NAN doesn't seem to be defined.

**Comment by denzelwamburu** [comment]
Do i need to define it from my function or? i thought it is already defined in <math.h>

**Comment by robertinant** [comment]
Please see comment and potential work-around in this thread: https://github.com/finitespace/BME280/issues/24
