### ISSUE TITLE
I am using msp430 launchpad  and i want to change spi module from UCB0 to UCA0. What should i do???

### ISSUE THREAD

**Issue by hemangjoshi37a** [energia/Energia#973]
I want to use spi and i2c communication in one page of code. But the pins of I2c and spi communiction are crossing each other. So now i  need to change my spi module to another port ie : from port:B to port:A
Please help me.
Thank you..

**Comment by rei-vilo** [comment]
Which exact MCU are you using? Please use the template provided when opening a new ticket.

Four options:

* Use Code Composer Studio, which provides access to all resources of the MCUs.
* Pay visit to the [43oh forum](http://forum.43oh.com) and [perform a search](http://forum.43oh.com/search/?&q=UCB0%20UCA0&sortby=relevancy)
* Edit the files of Energia corresponding to the SPI library.
* Use software SPI with [shiftOut()](http://energia.nu/reference/shiftout/) and [shiftIn()](http://energia.nu/reference/shiftin/)

**Comment by hemangjoshi37a** [comment]
@rei-vilo
Okay bro. Sure....
