### ISSUE TITLE
Code for SD card isnt working on MSP430. Does anyone have an energia library of SD data logger for MSP430 or MSP430 

### ISSUE THREAD

**Issue by DarthVerma** [energia/Energia#977]
Thank you for opening an issue on the Energia repository. 

### Do not use GitHub issues for project related questions. 

Use instead the [43oh forum](http://forum.43oh.com) and [TI E2E forum](http://e2e.ti.com), so everyone can share the questions and answers.

### Do not use GitHub issues for questions on third-party libraries. 

Use instead their own repositories.

### Check the issue hasn't been reported yet.

If an issue has alreday been reported, add your case to its thread.

### Please provide the following information.

* LaunchPad board name and version: `INSERT LAUNCHPAD BOARD NAME AND VERSION`
* Energia IDE version (found in Energia > About Energia menu): `INSERT ENERGIA VERSION`
* Board package version (found in Tools > Boards > Boards Manager menu): `INSERT BOARD PACKAGE VERSION`
* OS name and version: `INSERT OS NAME AND VERSION`

### Describe the expected results.

`INSERT DESCRIPTION OF THE EXPECTED RESULT`

### Describe the actual results.

`INSERT DESCRIPTION OF THE ACTUAL RESULT`

### List the steps to reproduce the problem.

`INSERT STEPS TO REPRODUCE THE PROBLEM`

**Comment by rei-vilo** [comment]
Please post your question at the 43oh forum.
