### ISSUE TITLE
I2C Slave MSP430g2553

### ISSUE THREAD

**Issue by phillip-shvartsman** [energia/Energia#988]
Does the I2C slave using Wire library work on the MSP430g2553. I'm having trouble using it, and there is another issue stating there are bugs. Does anyone have any working code or is it impossible? I know this is an inappropriate issue, just need some sort of communication with someone who has experience with this software. Thank you.

**Comment by rei-vilo** [comment]
Yes, I²C slave works.

Please post your question at the http://43oh.com forum.
