### ISSUE TITLE
MSP430F5529 flash memory overflow

### ISSUE THREAD

**Issue by manaioussema** [energia/Energia#994]
Hello everyone,
Lastly when i was uploading my code to the MSP430F5529 launchpad the compiler through this error message:
![capture](https://user-images.githubusercontent.com/26526121/34554892-609641d6-f12f-11e7-982b-5fe616bc4c22.JPG)

is there any solution for this ? thank you in advance.

**Comment by robertinant** [comment]
You are using more flash space then is available. The only solution is to reduce the size of your Sketch. Note that the current compiler is only capable of utilizing the lower 48k. So even if the micro controller has more than 48k you will only be able to use 48k of that memory.

**Comment by manaioussema** [comment]
any solution ?

**Comment by rei-vilo** [comment]
Either use a LaunchPad with more flash or reduce the size of the executable.

For project-related questions, please post your question at the www.43oh.com forum.

**Comment by manaioussema** [comment]
any idea about when the compiler will be updated ?

**Comment by rei-vilo** [comment]
If your project is in a hurry, when don't you use CCS instead?

**Comment by manaioussema** [comment]
i'm using a menu library that's not easy to port to CCS.
