### ISSUE TITLE
Failed: Unable to find an entry in the TPI ini file for "TMS470REX"

### ISSUE THREAD

**Issue by imrahulr** [energia/Energia#996]
LaunchPad board name and version: TIVA 4C123G
Energia IDE version (found in Energia > About Energia menu): 1.6.10E18
OS name and version: Windows7

While uploading the example Blink code on Tiva 4C123G evaluation board, I get an error  "Failed: Unable to find an entry in the TPI ini file for "TMS470REX" ", failing to upload to the device. 

Please help!

**Comment by robertinant** [comment]
Please do not double post. We did get your message on the forum here: https://forum.43oh.com/topic/13010-failed-unable-to-find-an-entry-in-the-tpi-ini-file-for-tms470rex/
I asked for additional information in that thread.
