### ISSUE TITLE
I am getting the following error while uploading a sketch for cc3200 in energia." Opening COM6 Triggering bootloader.... Trigger bootloader failed. Retrying... (1 attempt) Trigger bootloader failed. Retrying... (2 attempt) Trigger bootloader failed. Retrying... (3 attempt) Trigger bootloader failed after 3 attempts Failed to trigger bootloader An error occurred while uploading the sketch ." I have shorted TCK and SOP2 .Can u tell me how to overcome this problem?

### ISSUE THREAD

**Issue by YATHIK** [energia/Energia#997]
Thank you for opening an issue on the Energia repository. 

### Do not use GitHub issues for project related questions. 

Use instead the [43oh forum](http://forum.43oh.com) and [TI E2E forum](http://e2e.ti.com), so everyone can share the questions and answers.

### Do not use GitHub issues for questions on third-party libraries. 

Use instead their own repositories.

### Check the issue hasn't been reported yet.

If an issue has alreday been reported, add your case to its thread.

### Please provide the following information.

* LaunchPad board name and version: `INSERT LAUNCHPAD BOARD NAME AND VERSION`
* Energia IDE version (found in Energia > About Energia menu): `INSERT ENERGIA VERSION`
* Board package version (found in Tools > Boards > Boards Manager menu): `INSERT BOARD PACKAGE VERSION`
* OS name and version: `INSERT OS NAME AND VERSION`

### Describe the expected results.

`INSERT DESCRIPTION OF THE EXPECTED RESULT`

### Describe the actual results.

`INSERT DESCRIPTION OF THE ACTUAL RESULT`

### List the steps to reproduce the problem.

`INSERT STEPS TO REPRODUCE THE PROBLEM`

**Comment by robertinant** [comment]
Do you have the right comport selected. Also, make sure that the jumper wire is installed correctly as per guide here: http://energia.nu/cc3200guide/
Next time when posting please do not use the title to describe. Also please use the forum here https://forum.43oh.com/forum/125-energia-tivaccc3xxx/ to ask question and we will help to determine if it is indeed a bug. If it is, then you can use the github issue page to report an issue.
